"""Storage Management Step 1 — server-generated document object keys.

The storage object name is **generated by CarbonTally** and never derived from
the user-supplied file name for security-sensitive path identity:

    uploads/{organization_id}/{YYYY}/{MM}/{DD}/{uuid4_hex}{.ext}

* The ``uploads/{organization_id}/...`` prefix is preserved deliberately — the
  ratified D32 storage predicate authorises exactly that prefix for the client
  organisation's active members, so the client organisation remains the storage
  tenancy anchor and no consultant namespace is introduced.
* ``organization_id`` is validated as a UUID-shaped token before it is used, so
  a caller can never inject path segments through the tenant identifier.
* The original user file name is preserved **as metadata/provenance only**
  (:func:`sanitize_display_name`) and is never part of the object key.
* The same builder is used by every writer, so a new ingress cannot silently
  introduce a second path convention.

Read-only helpers here; no storage call is made by this module.
"""
from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Optional
from uuid import uuid4

#: The bucket every document object lives in (D32 — private).
DOCUMENTS_BUCKET = "documents"

#: Canonical first path segment.  Pinned by the ratified D32 storage policy
#: (``foldername(name)[1] = 'uploads'``) and asserted by
#: ``20260823000000_d32_private_documents_storage.sql``.
DOCUMENT_KEY_ROOT = "uploads"

#: Longest display name kept for provenance.
MAX_DISPLAY_NAME_LENGTH = 255

#: Longest extension accepted into a generated key.
MAX_EXTENSION_LENGTH = 8

_UUID_TOKEN = re.compile(r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-"
                         r"[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")
_UUID_OR_ALNUM = re.compile(r"^[A-Za-z0-9_-]{1,64}$")
_EXTENSION = re.compile(r"^[a-z0-9]{1,%d}$" % MAX_EXTENSION_LENGTH)
_UNSAFE_NAME_CHARS = re.compile(r"[\x00-\x1f\x7f]")
_PATH_SEPARATORS = ("/", "\\")


def is_valid_tenant_token(organization_id: str) -> bool:
    """Whether ``organization_id`` is a UUID or a safe single-segment token.

    Production tenants are UUIDs; a slug token is tolerated only so in-memory
    and development fixtures keep working.  Either way the value may contain no
    path separator, so a caller can never inject key segments.
    """
    token = str(organization_id or "")
    return bool(_UUID_TOKEN.match(token) or _UUID_OR_ALNUM.match(token))


def _tenant_segment(organization_id: str) -> str:
    """Return the validated tenant path segment (raises ``ValueError``)."""
    token = str(organization_id or "")
    if not is_valid_tenant_token(token):
        raise ValueError("organization_id is not a valid storage tenant token")
    return token



def split_extension(filename: Optional[str]) -> str:
    """Return the sanitised, lower-cased extension of ``filename`` (``""``).

    Only ``[a-z0-9]`` characters of at most :data:`MAX_EXTENSION_LENGTH` survive;
    anything else yields ``""`` so an object key can never carry injected
    segments.
    """
    if not filename or "." not in filename:
        return ""
    candidate = filename.rsplit(".", 1)[-1].strip().lower()
    return candidate if _EXTENSION.match(candidate) else ""


def is_safe_filename(filename: Optional[str]) -> bool:
    """Whether ``filename`` is acceptable as provenance.

    Rejects NUL/control characters, path separators and traversal segments.  The
    object key never depends on this value, so this is defence in depth.
    """
    if not filename:
        return False
    name = str(filename)
    if _UNSAFE_NAME_CHARS.search(name):
        return False
    if any(sep in name for sep in _PATH_SEPARATORS):
        return False
    if name in (".", ".."):
        return False
    return len(name) <= MAX_DISPLAY_NAME_LENGTH


def sanitize_display_name(filename: Optional[str]) -> str:
    """Return a single-segment, control-character-free display name."""
    if not filename:
        return ""
    name = str(filename)
    for sep in _PATH_SEPARATORS:
        name = name.replace(sep, "_")
    name = _UNSAFE_NAME_CHARS.sub("_", name).strip()
    if name in (".", ".."):
        name = f"_{name.strip('.') or 'file'}"
    return name[:MAX_DISPLAY_NAME_LENGTH]


def build_document_storage_key(
    organization_id: str,
    filename: Optional[str] = None,
    *,
    now: Optional[datetime] = None,
    token: Optional[str] = None,
) -> str:
    """Return the canonical, server-generated object key for a new upload.

    ``token`` is injectable for deterministic tests; production always uses a
    fresh ``uuid4().hex``.
    """
    tenant = _tenant_segment(organization_id)
    moment = now or datetime.now(timezone.utc)
    unique = token or uuid4().hex
    if not re.match(r"^[a-f0-9]{16,64}$", unique):
        raise ValueError("storage key token must be a hex token")
    extension = split_extension(filename)
    suffix = f".{extension}" if extension else ""
    return (
        f"{DOCUMENT_KEY_ROOT}/{tenant}/"
        f"{moment.strftime('%Y')}/{moment.strftime('%m')}/{moment.strftime('%d')}/"
        f"{unique}{suffix}"
    )


def key_belongs_to_organization(key: str, organization_id: str) -> bool:
    """Whether ``key`` is a well-formed document key for ``organization_id``."""
    if not key:
        return False
    parts = str(key).split("/")
    if len(parts) != 6 or parts[0] != DOCUMENT_KEY_ROOT:
        return False
    try:
        tenant = _tenant_segment(organization_id)
    except ValueError:
        return False
    return parts[1] == tenant


def organization_id_from_key(key: str) -> Optional[str]:
    """Extract the tenant segment from a canonical document key (``None``)."""
    parts = str(key or "").split("/")
    if len(parts) != 6 or parts[0] != DOCUMENT_KEY_ROOT:
        return None
    return parts[1]


#: Path segment that marks a **derived** artefact (repaired/optimised/rendered
#: output) as distinct from the customer's original uploaded evidence.
DERIVED_KEY_SEGMENT = "derived"


def build_derived_artifact_key(
    organization_id: str,
    filename: Optional[str] = None,
    *,
    token: Optional[str] = None,
) -> str:
    """Return a key for a **derived** artefact in the client organisation's namespace.

    Step 2P: a repaired / OCR-rendered / optimised output is a *distinct* object
    from the customer's original evidence, so it gets its own key and can never
    be mistaken for (or overwrite) the original:

        uploads/{organization_id}/derived/{uuid4_hex}{.ext}

    The key keeps the ratified ``uploads/{tenant}/...`` layout, so the D32
    storage-RLS predicate (``foldername(name)[1] = 'uploads'`` plus the
    organisation-membership check on segment 2) still governs it — a derived
    artefact stays under the same client organisation ownership model and never
    becomes a consultant-owned tenancy.
    """
    tenant = _tenant_segment(organization_id)
    unique = token or uuid4().hex
    if not re.match(r"^[a-f0-9]{16,64}$", unique):
        raise ValueError("storage key token must be a hex token")
    extension = split_extension(filename)
    suffix = f".{extension}" if extension else ""
    return f"{DOCUMENT_KEY_ROOT}/{tenant}/{DERIVED_KEY_SEGMENT}/{unique}{suffix}"


def is_derived_artifact_key(key: str) -> bool:
    """Whether ``key`` is a well-formed derived-artefact key."""
    parts = str(key or "").split("/")
    return (
        len(parts) == 4
        and parts[0] == DOCUMENT_KEY_ROOT
        and parts[2] == DERIVED_KEY_SEGMENT
        and bool(parts[3])
    )
