"""Storage Management Step 1C — direct-to-storage (signed) document upload.

The preferred upload pattern, implemented end to end server-side:

1. the browser asks CarbonTally to **start** an upload;
2. the backend authenticates and authorizes through the single upload gate
   (``api.upload_gate``) — organisation membership, or an active consultant
   grant plus the consultant's ``can_upload_documents`` capability;
3. the backend validates the proposed file name, extension, declared content
   type and size against the canonical admin-configurable upload policy;
4. the backend creates the ``organization_files`` row in ``pending_upload``;
5. the backend issues a **short-lived, object-scoped signed upload URL**;
6. the browser uploads the bytes **directly to Supabase Storage** — the backend
   never proxies the ordinary upload byte stream and never hands the
   service-role credential to the browser;
7. the browser confirms completion; the backend verifies the object exists,
   checks its real size, runs the security gate, and only then advances the
   document to ``clean`` and enqueues processing — or marks it ``rejected``
   (quarantined) and refuses it.

The storage path is **generated by CarbonTally** (``services.storage_keys``); a
client-supplied path is never accepted and the user file name is provenance
only.  A candidate upload is scoped to the client organisation's namespace —
there is no consultant bucket and no consultant-owned tenancy.

Resumable (TUS) uploads are deliberately not enabled in Step 1: the ratified
per-file cap is 10 MiB, an ordinary signed PUT covers that comfortably, and a
TUS session would require exposing a storage-level credential (project key or
user JWT) to the browser.  The response advertises this explicitly rather than
silently implying resumability.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field

from api.consultant_auth import ConsultantContext, require_consultant
from api.dependencies import RepositoryBundle, get_repositories
from api.upload_gate import (
    ACTION_ACCEPTED,
    ACTION_DOWNLOAD,
    ACTION_SCAN_UNAVAILABLE,
    ACTION_SECURITY_REJECTED,
    ACTION_SECURITY_SCAN_COMPLETED,
    ACTION_SECURITY_SCAN_STARTED,
    ACTION_UPLOAD_COMPLETED,
    ACTION_UPLOAD_EXPIRED,
    ACTION_UPLOAD_INITIATED,
    UploadActor,
    authorize_consultant_upload,
    authorize_organization_upload,
    record_document_event,
)
from api.v3_documents import (
    _classify,
    _renderable_content_type,
    enqueue_document_processing,
)
from auth import AuthUser, get_current_user, require_org_member
from services.document_security import (
    ALLOWED_DOCUMENT_EXTENSIONS,
    SCAN_STATE_SCANNER_ERROR,
    SCAN_STATE_SCANNER_UNAVAILABLE,
    STATUS_CLEAN,
    STATUS_FAILED,
    STATUS_PENDING_UPLOAD,
    STATUS_PROCESSING,
    STATUS_REJECTED,
    STATUS_UPLOAD_EXPIRED,
    rejection_detail,
    scan_document,
)
from services.document_security import external_scan_status
from services.storage import (
    DOCUMENTS_BUCKET,
    SIGNED_UPLOAD_TTL_SECONDS,
    UPLOAD_COMPLETION_WINDOW_SECONDS,
    create_signed_upload_url,
    download_object,
    download_object_prefix,
    object_info,
    stored_object_size,
)
from services.storage_keys import (
    build_document_storage_key,
    is_safe_filename,
    key_belongs_to_organization,
    sanitize_display_name,
    split_extension,
)
from utils.document_classifier import classify_document
from utils.upload_limits import effective_file_limit_bytes, resolve_policy

router = APIRouter(prefix="/api/v3", tags=["V3 — Document uploads (signed)"])

#: Why resumable uploads are not offered in Step 1 (advertised to clients).
RESUMABLE_UNSUPPORTED_REASON = (
    "resumable/TUS upload is not enabled: the ratified per-file limit is 10 MiB, "
    "which a signed PUT covers, and a TUS session would require exposing a "
    "storage-level credential to the browser. Deferred to Step 2."
)


class OrganizationUploadRequest(BaseModel):
    """Start a direct upload for the caller's own organisation."""

    organization_id: str
    filename: str
    size_bytes: int = Field(ge=0)
    content_type: str = "application/octet-stream"
    data_type: str = "utility"
    #: Optional explicit ``document_types.code``.  Omitted (the normal case):
    #: the file is auto-classified.  Supplied: the uploader's choice becomes the
    #: authoritative classification and is recorded as ``user_selected``, so an
    #: override is auditable and never indistinguishable from an auto result.
    document_type_code: Optional[str] = Field(default=None, max_length=64)


class ConsultantUploadRequest(BaseModel):
    """Start a direct upload for an active, authorized client organisation."""

    filename: str
    size_bytes: int = Field(ge=0)
    content_type: str = "application/octet-stream"
    data_type: str = "utility"
    #: Optional explicit ``document_types.code`` (see ``OrganizationUploadRequest``).
    document_type_code: Optional[str] = Field(default=None, max_length=64)


class UploadCompleteRequest(BaseModel):
    """Confirm that the browser finished the direct upload."""

    size_bytes: Optional[int] = Field(default=None, ge=0)


# ---------------------------------------------------------------------------
# shared helpers
# ---------------------------------------------------------------------------


def _attr(record: Any, name: str, default: Any = None) -> Any:
    """Read a field from a domain object or a mapping (see v3_documents)."""
    if isinstance(record, dict):
        return record.get(name, default)
    return getattr(record, name, default)


async def _set_document_status(
    repos: Any, document_id: str, status: str, size_bytes: Optional[int] = None
) -> None:
    """Advance the document lifecycle state (best-effort, never fatal)."""
    update = getattr(getattr(repos, "files", None), "update_status", None)
    if not document_id or not callable(update):
        return
    try:
        if size_bytes is None:
            await update(document_id, status)
        else:
            await update(document_id, status, size_bytes)
    except Exception as exc:  # noqa: BLE001 - lifecycle bookkeeping is best-effort
        print(f"could not set document {document_id} status to {status}: {exc!r}")



async def _effective_limit_bytes(repos: Any) -> tuple[int, int]:
    """Return ``(limit_mb, limit_bytes)`` from the canonical upload policy."""
    policy = await resolve_policy(getattr(repos, "settings", None))
    limit_mb = policy["max_file_size_mb"]
    return limit_mb, effective_file_limit_bytes(limit_mb)


def _oversize_detail(filename: str, size_bytes: int, limit_mb: int) -> str:
    """Clear, actionable size error — the original is never compressed."""
    return (
        f"'{filename}' is {size_bytes / (1024 * 1024):.1f}MB; the platform limit "
        f"is {limit_mb}MB per file. The original document is never compressed "
        "server-side — please upload a smaller file or split the document."
    )


def _upload_window_expired(record: Any) -> bool:
    """Whether a ``pending_upload`` row is past its completion window.

    Rows without an ``uploaded_at`` value (in-memory/dev fixtures) are treated as
    fresh: the window is an abandonment rule for real uploads, not a way to
    reject anything the platform cannot date.
    """
    started = _attr(record, "uploaded_at")
    if not isinstance(started, datetime):
        return False
    if started.tzinfo is None:
        started = started.replace(tzinfo=timezone.utc)
    age = (datetime.now(timezone.utc) - started).total_seconds()
    return age > UPLOAD_COMPLETION_WINDOW_SECONDS

# ---------------------------------------------------------------------------
# advisory document-type classification
# ---------------------------------------------------------------------------
#
# Every uploaded file is classified against the EXISTING CarbonTally document
# taxonomy (``utils.document_classifier`` over the ``document_types`` reference
# table) so the user is told what CarbonTally believes the document is — without
# an upload-blocking "Data type" choice.
#
# The verdict is advisory and best-effort. The authoritative decision is still
# made downstream by extraction → mapping → validation, and an upload is never
# refused because the taxonomy could not be consulted.
#
# The processing pipeline is deliberately NOT influenced by this value:
# ``data_type`` (the processing hint passed to ``enqueue_document_processing``)
# keeps its existing value and behaviour.


def _unavailable_classification() -> dict:
    """The honest "not classified" verdict (never a fabricated type)."""
    return {
        "document_type_code": None,
        "document_type_id": None,
        "confidence": 0.0,
        "suggested_type": None,
        "category": None,
        "source": "unavailable",
        "alternative_types": [],
    }


async def _classify_upload(
    filename: str, document_type_code: Optional[str] = None
) -> dict:
    """Classify one uploaded file against the existing document taxonomy.

    ``document_type_code`` is an optional explicit choice; the classifier records
    it as ``source="user_selected"`` so an override is auditable.  When omitted
    the classifier decides from the document itself.

    Best-effort by design: the taxonomy is reference data that may not be
    configured in a given deployment, so a classification failure degrades to
    ``source="unavailable"`` rather than failing the upload.
    """
    try:
        return await classify_document(filename, None, document_type_code)
    except Exception as exc:  # noqa: BLE001 - classification is advisory
        print(f"⚠️ document classification unavailable for {filename}: {exc!r}")
        return _unavailable_classification()


# ---------------------------------------------------------------------------
# initiation
# ---------------------------------------------------------------------------


async def _start_upload(
    *,
    actor: UploadActor,
    repos: Any,
    filename: str,
    size_bytes: int,
    content_type: str,
    data_type: str,
    completion_path: str,
    client_id: Optional[str] = None,
    document_type_code: Optional[str] = None,
) -> dict:
    """Validate, record the pending document, and issue the signed upload URL."""
    if not is_safe_filename(filename):
        raise HTTPException(
            status_code=422,
            detail=(
                "the file name contains path separators or control characters; "
                "the storage object name is generated by CarbonTally and the "
                "original name is kept as provenance only"
            ),
        )
    extension = split_extension(filename)
    if extension not in ALLOWED_DOCUMENT_EXTENSIONS:
        raise HTTPException(
            status_code=422,
            detail=(
                f"'.{extension}' is not an allowed document extension"
                if extension
                else "the upload has no file extension"
            ),
        )
    if size_bytes <= 0:
        raise HTTPException(
            status_code=400, detail="size_bytes must be greater than zero"
        )
    limit_mb, limit_bytes = await _effective_limit_bytes(repos)
    if size_bytes > limit_bytes:
        raise HTTPException(
            status_code=413, detail=_oversize_detail(filename, size_bytes, limit_mb)
        )

    file_type = _classify(filename, content_type)
    try:
        path = build_document_storage_key(actor.organization_id, filename)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=f"invalid upload target: {exc}")
    mime_type = _renderable_content_type(filename, file_type, content_type)
    provenance = actor.provenance()
    # Advisory, best-effort document-type verdict.  It never gates the upload and
    # never changes what the processing pipeline is asked to do.
    classification = await _classify_upload(filename, document_type_code)
    record = await repos.files.create(
        org_id=actor.organization_id,
        name=sanitize_display_name(filename),
        path=path,
        size_bytes=size_bytes,
        file_type=file_type,
        mime_type=mime_type,
        bucket=DOCUMENTS_BUCKET,
        uploaded_by=actor.user_id,
        status=STATUS_PENDING_UPLOAD,
        metadata={
            "data_type": data_type,
            "file_url": path,
            "original_filename": filename,
            "upload_mode": "signed_direct",
            "security_gate": {"verdict": "pending", "scanner": None},
            # The classification verdict is persisted so it survives the upload and
            # is auditable even if the bytes never arrive (see abandon).
            "classification": classification,
            **provenance,
        },
    )
    document_id = str(_attr(record, "id") or "")

    signed = create_signed_upload_url(path)
    if not signed or not signed.get("url"):
        await _set_document_status(repos, document_id, STATUS_FAILED)
        await record_document_event(
            repos=repos,
            action=ACTION_UPLOAD_INITIATED,
            actor=actor,
            organization_id=actor.organization_id,
            entity_id=document_id,
            changed_fields={**provenance, "filename": filename, "storage_path": path},
            reason="no signed upload URL could be issued; the upload was not authorised",
            outcome="failure",
        )
        raise HTTPException(
            status_code=503,
            detail="storage upload authorisation is unavailable; nothing was accepted",
        )

    await record_document_event(
        repos=repos,
        action=ACTION_UPLOAD_INITIATED,
        actor=actor,
        organization_id=actor.organization_id,
        entity_id=document_id,
        changed_fields={
            **provenance,
            "filename": filename,
            "size_bytes": size_bytes,
            "declared_mime": content_type,
            "storage_path": path,
            "bucket": DOCUMENTS_BUCKET,
            "status": STATUS_PENDING_UPLOAD,
            "ingress": "signed_direct_upload",
            "signed_url_declared_ttl_seconds": SIGNED_UPLOAD_TTL_SECONDS,
        },
        reason="document upload initiated; short-lived signed upload URL issued",
    )
    return {
        "document_id": document_id,
        "organization_id": actor.organization_id,
        "client_id": client_id,
        "bucket": DOCUMENTS_BUCKET,
        "storage_path": path,
        "filename": filename,
        "status": STATUS_PENDING_UPLOAD,
        "upload_mode": "signed_direct",
        "max_size_bytes": limit_bytes,
        # CT-PO-UPLOAD-UNIFY-001 — the caller is told what CarbonTally classified
        # the document as, so a multi-file upload can report it per file.
        "classification": classification,
        # Step 2D — the caller is told exactly what will scan the bytes.  The
        # platform never implies a vendor malware scan it will not perform.
        "security_gate": external_scan_status(),
        "upload": {
            "url": signed["url"],
            "token": signed["token"],
            "method": "PUT",
            "expires_in_seconds": SIGNED_UPLOAD_TTL_SECONDS,
            "headers": {"x-upsert": "false", "content-type": mime_type},
        },
        "completion": {
            "method": "POST",
            "path": completion_path,
            "must_complete_within_seconds": UPLOAD_COMPLETION_WINDOW_SECONDS,
        },
        "resumable": {"supported": False, "reason": RESUMABLE_UNSUPPORTED_REASON},
    }


# ---------------------------------------------------------------------------
# completion (verification + security gate)
# ---------------------------------------------------------------------------


async def _complete_upload(
    *,
    actor: UploadActor,
    repos: Any,
    document_id: str,
    client_id: Optional[str] = None,
) -> dict:
    """Verify a browser-completed direct upload and run the security gate."""
    doc = await repos.files.get(document_id)
    if doc is None:
        raise HTTPException(status_code=404, detail="document not found")

    doc_organization = str(_attr(doc, "organization_id") or "")
    if doc_organization != actor.organization_id:
        await record_document_event(
            repos=repos,
            action=ACTION_DOWNLOAD,
            actor=actor,
            organization_id=actor.organization_id,
            entity_id=document_id,
            changed_fields={"document_organization_id": doc_organization},
            reason="upload completion refused: document belongs to another organisation",
            outcome="failure",
        )
        raise HTTPException(status_code=403, detail="Organization access denied")

    current_status = _attr(doc, "status")
    if current_status in (STATUS_CLEAN, STATUS_PROCESSING):
        return {
            "document_id": document_id,
            "status": current_status,
            "idempotent": True,
            "client_id": client_id,
            # The verdict recorded when the upload was started, so a re-entrant
            # completion reports the same classification as the first one.
            "classification": dict(_attr(doc, "metadata") or {}).get("classification")
            or _unavailable_classification(),
        }
    if current_status != STATUS_PENDING_UPLOAD:
        raise HTTPException(
            status_code=409,
            detail=(
                f"document is in status '{current_status}' and cannot be completed; "
                "only a pending upload can be completed"
            ),
        )
    if _upload_window_expired(doc):
        raise HTTPException(
            status_code=409,
            detail=(
                "the upload authorisation has expired; nothing was accepted — "
                "start a new upload"
            ),
        )

    path = str(_attr(doc, "path") or "")
    filename = str(_attr(doc, "name") or "")
    if not key_belongs_to_organization(path, doc_organization):
        raise HTTPException(
            status_code=409,
            detail=(
                "the document's storage path is not a canonical CarbonTally "
                "document key for this organisation; nothing was accepted"
            ),
        )
    limit_mb, limit_bytes = await _effective_limit_bytes(repos)

    info = object_info(path)
    if info is None:
        raise HTTPException(
            status_code=409,
            detail="no object was found at the upload target; nothing was accepted",
        )
    actual_size = stored_object_size(info)
    if not actual_size:
        await _set_document_status(repos, document_id, STATUS_REJECTED)
        await record_document_event(
            repos=repos,
            action=ACTION_SECURITY_REJECTED,
            actor=actor,
            organization_id=doc_organization,
            entity_id=document_id,
            changed_fields={"storage_path": path, "storage_info": info},
            reason="malformed or truncated upload: the stored object has no usable size",
            outcome="failure",
        )
        raise HTTPException(
            status_code=409,
            detail="the uploaded object is empty or truncated; nothing was accepted",
        )
    if actual_size > limit_bytes:
        await _set_document_status(repos, document_id, STATUS_REJECTED)
        await record_document_event(
            repos=repos,
            action=ACTION_SECURITY_REJECTED,
            actor=actor,
            organization_id=doc_organization,
            entity_id=document_id,
            changed_fields={"storage_path": path, "actual_size_bytes": actual_size},
            reason=_oversize_detail(filename, actual_size, limit_mb),
            outcome="failure",
        )
        raise HTTPException(
            status_code=413, detail=_oversize_detail(filename, actual_size, limit_mb)
        )

    await record_document_event(
        repos=repos,
        action=ACTION_SECURITY_SCAN_STARTED,
        actor=actor,
        organization_id=doc_organization,
        entity_id=document_id,
        changed_fields={"storage_path": path, "actual_size_bytes": actual_size},
        reason="security gate started after the direct upload completed",
    )
    probed = None
    try:
        probed = download_object(path, max_bytes=limit_bytes)
    except TypeError:  # pragma: no cover - a legacy single-argument double
        probed = download_object(path)
    if probed is None:
        probed = download_object_prefix(path)
    if probed is None:
        raise HTTPException(
            status_code=409,
            detail="the uploaded object could not be read back; nothing was accepted",
        )
    # Step 2J — the same bytes feed BOTH the security gate and the downstream
    # processing pipeline, so a directly-uploaded document receives exactly the
    # same page count and OCR prefill as a server-proxied upload.  The read is
    # bounded by the ratified per-file ceiling and nothing is written back, so
    # the stored object remains the customer's unmodified original evidence.
    verdict = scan_document(
        content=probed,
        filename=filename,
        declared_mime=str(_attr(doc, "mime_type") or ""),
        extension=split_extension(filename),
    )
    await record_document_event(
        repos=repos,
        action=ACTION_SECURITY_SCAN_COMPLETED,
        actor=actor,
        organization_id=doc_organization,
        entity_id=document_id,
        changed_fields={"security_gate": verdict.as_metadata()},
        reason=f"security gate verdict: {verdict.verdict}",
        outcome="success" if verdict.accepted else "failure",
    )
    if not verdict.accepted:
        await _set_document_status(repos, document_id, STATUS_REJECTED)
        await record_document_event(
            repos=repos,
            action=ACTION_SECURITY_REJECTED,
            actor=actor,
            organization_id=doc_organization,
            entity_id=document_id,
            changed_fields={
                "security_gate": verdict.as_metadata(),
                "storage_path": path,
            },
            reason=rejection_detail(verdict),
            outcome="failure",
        )
        # Step 2D — say exactly WHY a required scan could not be established,
        # rather than reporting a generic rejection or (worse) an acceptance.
        if verdict.scan_state in (
            SCAN_STATE_SCANNER_UNAVAILABLE,
            SCAN_STATE_SCANNER_ERROR,
        ):
            await record_document_event(
                repos=repos,
                action=ACTION_SCAN_UNAVAILABLE,
                actor=actor,
                organization_id=doc_organization,
                entity_id=document_id,
                changed_fields={
                    "scan_state": verdict.scan_state,
                    "scanner": verdict.scanner,
                    "scanner_error": verdict.scanner_error,
                    "document_status": STATUS_REJECTED,
                },
                reason=(
                    "the document is quarantined because the required malware "
                    "scan could not be obtained; no malware-free status is claimed"
                ),
                outcome="failure",
            )
        raise HTTPException(status_code=422, detail=rejection_detail(verdict))

    await _set_document_status(repos, document_id, STATUS_CLEAN, actual_size)
    await record_document_event(
        repos=repos,
        action=ACTION_UPLOAD_COMPLETED,
        actor=actor,
        organization_id=doc_organization,
        entity_id=document_id,
        changed_fields={
            "storage_path": path,
            "bucket": DOCUMENTS_BUCKET,
            "actual_size_bytes": actual_size,
            "status": STATUS_CLEAN,
        },
        reason="direct upload verified and accepted by the security gate",
    )
    await record_document_event(
        repos=repos,
        action=ACTION_ACCEPTED,
        actor=actor,
        organization_id=doc_organization,
        entity_id=document_id,
        changed_fields={"status": STATUS_CLEAN, "filename": filename},
        reason="document accepted for normal CarbonTally processing",
    )

    # Only a security-cleared document enters the durable processing pipeline.
    merged_metadata = dict(_attr(doc, "metadata") or {})
    merged_metadata["security_gate"] = verdict.as_metadata()
    merged_metadata["verified_size_bytes"] = actual_size
    # CT-PO-UPLOAD-UNIFY-001 — the classification decided at initiation is carried
    # through to the completion payload.  It is metadata only: the processing
    # pipeline is enqueued with exactly the same arguments as before.
    classification = merged_metadata.get("classification") or _unavailable_classification()
    try:
        await repos.files.update_metadata(document_id, merged_metadata)
    except Exception as exc:  # noqa: BLE001 - metadata write is best-effort
        print(f"could not record the security verdict on {document_id}: {exc!r}")
    # Step 2J — pass the verified bytes so the shared pipeline computes the real
    # page count and runs the OCR prefill exactly as it does for a proxied
    # upload.  The identical downstream semantics are the point: a direct upload
    # must not silently lose processing functionality.
    await enqueue_document_processing(
        record={"id": document_id, "metadata": merged_metadata},
        document_id=document_id,
        organization_id=doc_organization,
        filename=filename,
        content=probed,
        mime_type=str(_attr(doc, "mime_type") or "application/octet-stream"),
        file_type=str(_attr(doc, "file_type") or "OTHER"),
        data_type=str(merged_metadata.get("data_type") or "utility"),
        uploaded_by=actor.user_id,
        repos=repos,
        storage_path=path,
    )

    # Step 2N — refresh the EXISTING storage-metering snapshot so the
    # admin-configurable capacity (billing_plans.included_storage_bytes) sees
    # this document.  Best-effort by design: commercial metering must never fail
    # an accepted upload, and capacity is metered/billed rather than enforced as
    # an upload block (see services.storage_metering).
    metering: dict = {}
    try:
        from services.storage_metering import record_storage_usage

        metering = await record_storage_usage(repos, doc_organization)
    except Exception as exc:  # noqa: BLE001 - never fail an accepted upload
        metering = {"recorded": False, "reason": str(exc)[:200]}

    return {
        "document_id": document_id,
        "organization_id": doc_organization,
        "client_id": client_id,
        "bucket": DOCUMENTS_BUCKET,
        "storage_path": path,
        "filename": filename,
        "status": STATUS_CLEAN,
        "size_bytes": actual_size,
        "security_gate": verdict.as_metadata(),
        "scan_state": verdict.scan_state,
        "external_scan_available": verdict.external_scan_available,
        "virus_scanned": verdict.external_scan_claimed(),
        "storage_metering": metering,
        "classification": classification,
        "idempotent": False,
    }


# ---------------------------------------------------------------------------
# abandonment (the terminal half of an upload that never completed)
# ---------------------------------------------------------------------------


async def _abandon_pending_upload(
    *,
    actor: UploadActor,
    repos: Any,
    document_id: str,
    client_id: Optional[str] = None,
) -> dict:
    """Move an abandoned ``pending_upload`` row to the terminal ``upload_expired`` state.

    CT-PO-UPLOAD-BATCH-REMEDIATION-001 — a direct upload creates its
    ``organization_files`` row *before* the browser PUTs the bytes, so a transport
    failure (the browser could not send the PUT, the tab was closed, the network
    dropped) leaves the row in ``pending_upload`` with no object behind it.  The
    24-hour completion window (:data:`services.storage.UPLOAD_COMPLETION_WINDOW_SECONDS`)
    already refuses to complete such a row later, and ``services.document_cleanup``
    already reaps it — but only when that pass runs.  This endpoint lets the *client
    that knows the upload failed* record the truth immediately, using the SAME
    terminal state and the SAME audit action the reaper uses:

    * the row is retained (never hard-deleted) — evidence is not destroyed;
    * ``pending_upload -> upload_expired`` is the existing ratified edge of
      :data:`services.document_security.STATUS_TRANSITIONS` (no invented state);
    * nothing is enqueued for processing and no object is touched;
    * it is refused (409) if an object actually exists at the upload target, so a
      real upload can never be mis-labelled as abandoned;
    * it is idempotent: an already-expired row returns ``idempotent: True``.
    """
    doc = await repos.files.get(document_id)
    if doc is None:
        raise HTTPException(status_code=404, detail="document not found")

    doc_organization = str(_attr(doc, "organization_id") or "")
    if doc_organization != actor.organization_id:
        await record_document_event(
            repos=repos,
            action=ACTION_UPLOAD_EXPIRED,
            actor=actor,
            organization_id=actor.organization_id,
            entity_id=document_id,
            changed_fields={"document_organization_id": doc_organization},
            reason="upload abandonment refused: document belongs to another organisation",
            outcome="failure",
        )
        raise HTTPException(status_code=403, detail="Organization access denied")

    current_status = _attr(doc, "status")
    if current_status == STATUS_UPLOAD_EXPIRED:
        return {
            "document_id": document_id,
            "status": STATUS_UPLOAD_EXPIRED,
            "abandoned": True,
            "idempotent": True,
            "client_id": client_id,
        }
    if current_status != STATUS_PENDING_UPLOAD:
        raise HTTPException(
            status_code=409,
            detail=(
                f"document is in status '{current_status}' and is not an abandoned "
                "upload; only a pending upload can be abandoned"
            ),
        )

    path = str(_attr(doc, "path") or "")
    if path and object_info(path) is not None:
        raise HTTPException(
            status_code=409,
            detail=(
                "an object exists at the upload target; this upload was not "
                "abandoned — confirm its completion instead"
            ),
        )

    await _set_document_status(repos, document_id, STATUS_UPLOAD_EXPIRED)
    await record_document_event(
        repos=repos,
        action=ACTION_UPLOAD_EXPIRED,
        actor=actor,
        organization_id=doc_organization,
        entity_id=document_id,
        changed_fields={
            "from_status": STATUS_PENDING_UPLOAD,
            "to_status": STATUS_UPLOAD_EXPIRED,
            "storage_path": path,
            "abandoned_by": "client",
        },
        reason=(
            "the browser reported that the direct upload did not reach storage; the "
            "row is retained but can no longer be completed, downloaded or processed"
        ),
    )
    return {
        "document_id": document_id,
        "organization_id": doc_organization,
        "client_id": client_id,
        "status": STATUS_UPLOAD_EXPIRED,
        "abandoned": True,
        "idempotent": False,
    }


# ---------------------------------------------------------------------------
# routes — organisation (direct customer) uploads
# ---------------------------------------------------------------------------


@router.post("/documents/upload-url", status_code=201)
async def start_organization_upload(
    payload: OrganizationUploadRequest,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
):
    """Start a direct upload for the caller's own organisation (Step 1C)."""
    actor = await authorize_organization_upload(
        current_user=current_user,
        organization_id=payload.organization_id,
        repos=repos,
    )
    return await _start_upload(
        actor=actor,
        repos=repos,
        filename=payload.filename,
        size_bytes=payload.size_bytes,
        content_type=payload.content_type,
        data_type=payload.data_type,
        document_type_code=payload.document_type_code,
        completion_path="/api/v3/documents/{document_id}/upload-complete",
    )


@router.post("/documents/{document_id}/upload-complete", status_code=200)
async def complete_organization_upload(
    document_id: str,
    payload: Optional[UploadCompleteRequest] = None,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
):
    """Verify a completed direct upload and run the security gate (Step 1C/1E)."""
    document = await repos.files.get(document_id)
    if document is None:
        raise HTTPException(status_code=404, detail="document not found")
    actor = await authorize_organization_upload(
        current_user=current_user,
        organization_id=str(_attr(document, "organization_id") or ""),
        repos=repos,
    )
    return await _complete_upload(actor=actor, repos=repos, document_id=document_id)


@router.post("/documents/{document_id}/upload-abandon", status_code=200)
async def abandon_organization_upload(
    document_id: str,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
):
    """Record that a direct upload never reached storage (CT-PO-UPLOAD-BATCH-REMEDIATION-001)."""
    document = await repos.files.get(document_id)
    if document is None:
        raise HTTPException(status_code=404, detail="document not found")
    actor = await authorize_organization_upload(
        current_user=current_user,
        organization_id=str(_attr(document, "organization_id") or ""),
        repos=repos,
    )
    return await _abandon_pending_upload(
        actor=actor, repos=repos, document_id=document_id
    )


# ---------------------------------------------------------------------------
# routes — consultant uploads for an authorized client
# ---------------------------------------------------------------------------


@router.post(
    "/consultants/clients/{client_id}/documents/upload-url", status_code=201
)
async def start_consultant_upload(
    client_id: str,
    payload: ConsultantUploadRequest,
    current_user: AuthUser = Depends(get_current_user),
    context: ConsultantContext = Depends(require_consultant),
    repos: RepositoryBundle = Depends(get_repositories),
):
    """Start a direct upload into an ACTIVE, authorized client's namespace.

    The client organisation remains the storage tenant; consultant provenance is
    recorded in application metadata only (Step 1H).
    """
    actor = await authorize_consultant_upload(
        current_user=current_user,
        consultant_context=context,
        client_id=client_id,
        repos=repos,
    )
    return await _start_upload(
        actor=actor,
        repos=repos,
        filename=payload.filename,
        size_bytes=payload.size_bytes,
        content_type=payload.content_type,
        data_type=payload.data_type,
        document_type_code=payload.document_type_code,
        client_id=client_id,
        completion_path=(
            f"/api/v3/consultants/clients/{client_id}/documents/"
            "{document_id}/upload-complete"
        ),
    )


@router.post(
    "/consultants/clients/{client_id}/documents/{document_id}/upload-complete",
    status_code=200,
)
async def complete_consultant_upload(
    client_id: str,
    document_id: str,
    payload: Optional[UploadCompleteRequest] = None,
    current_user: AuthUser = Depends(get_current_user),
    context: ConsultantContext = Depends(require_consultant),
    repos: RepositoryBundle = Depends(get_repositories),
):
    """Complete a consultant direct upload (the active grant is re-checked)."""
    actor = await authorize_consultant_upload(
        current_user=current_user,
        consultant_context=context,
        client_id=client_id,
        repos=repos,
    )
    return await _complete_upload(
        actor=actor, repos=repos, document_id=document_id, client_id=client_id
    )


@router.post(
    "/consultants/clients/{client_id}/documents/{document_id}/upload-abandon",
    status_code=200,
)
async def abandon_consultant_upload(
    client_id: str,
    document_id: str,
    current_user: AuthUser = Depends(get_current_user),
    context: ConsultantContext = Depends(require_consultant),
    repos: RepositoryBundle = Depends(get_repositories),
):
    """Record that a consultant direct upload never reached storage."""
    actor = await authorize_consultant_upload(
        current_user=current_user,
        consultant_context=context,
        client_id=client_id,
        repos=repos,
    )
    return await _abandon_pending_upload(
        actor=actor, repos=repos, document_id=document_id, client_id=client_id
    )
