"""V3 reports surface (V3 Phase 5).

The org-scoped reporting workflow built on the authoritative chain:

    Source → Extraction → Mapping → Factor matching → Calculation engine
        → Validation → Review → Approval → REPORT

Reports are generated by the authoritative ``ReportGenerationEngine`` (the
same engine behind ``POST /api/v2/generate-report``) from the persisted
``emissions_logs`` / ``calculation_snapshots`` data. The frontend never
calculates or fabricates content; every response below reads the persisted
``report_generation_queue`` row (lifecycle, provenance, artefact state) and the
``generated_content`` JSONB written by the engine.

Lifecycle (preserving the existing synchronous architecture — no worker
infrastructure)::

    QUEUED (pending) → GENERATING (transient) → READY (completed)
    QUEUED (pending) → GENERATING (transient) → FAILED (failed + error_log)

Generation is synchronous inside the request: the queue row is created first
(QUEUED), moved to ``generating``, then the engine completes it (READY). On any
failure the real error is persisted to ``error_log`` and the row is marked
``failed`` — nothing is presented as ready unless the backend confirms the row
is ``completed`` with persisted content.

Versioning reuses the existing ``report_versions`` table (V3M2 schema): a
snapshot row is recorded on every successful generation.

Export reuses the existing org-isolated ``/api/v3/exports/*`` surface (CSV/JSON)
— no second export implementation.
"""
from __future__ import annotations

from typing import Any, Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, ConfigDict, Field

from api.consultant_branding import resolve_report_branding
from api.dependencies import (
    RepositoryBundle,
    ensure_org_access,
    get_report_engine,
    get_repositories,
    require_org_member,
)
from auth import AuthUser
from domain.report import ReportRequest
from engines.pdf_render import render_branded_pdf
from engines.report_generation import ReportGenerationEngine

router = APIRouter(prefix="/api/v3/reports", tags=["V3 — Reports"])

#: Report types the V3 engine genuinely supports. The engine composes one
#: structured 12-section report (annual emissions) from the persisted logs;
#: the legacy generator's other labels (summary/documents/staff/...) have no V3
#: engine backing and are deliberately not offered.
SUPPORTED_REPORT_TYPES: dict[str, str] = {
    "annual": "Annual emissions report (structured 12-section V3 report)",
}

#: Queue statuses surfaced by the dashboard (persisted values on the existing
#: ``report_generation_queue.status`` column).
REPORT_STATUSES: tuple[str, ...] = ("pending", "generating", "completed", "failed")

#: Human-readable display labels for persisted statuses.
STATUS_LABELS: dict[str, str] = {
    "pending": "Queued",
    "generating": "Generating",
    "completed": "Ready",
    "failed": "Failed",
}


class ReportGenerateIn(BaseModel):
    """Request to generate a report (client never supplies the result)."""

    organization_id: str = Field(..., min_length=1)
    report_type: str = "annual"
    reporting_year: int = Field(..., ge=1990, le=2100)
    template_id: Optional[str] = None
    options: dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(extra="forbid")


# ---------------------------------------------------------------------------
# Helpers (pure — unit-tested without a database)
# ---------------------------------------------------------------------------


def validate_report_type(report_type: str) -> None:
    """Reject report types with no V3 engine/data backing (HTTP 422)."""
    if report_type not in SUPPORTED_REPORT_TYPES:
        raise HTTPException(
            status_code=422,
            detail=(
                f"unsupported report type {report_type!r}; "
                f"supported: {', '.join(sorted(SUPPORTED_REPORT_TYPES))}"
            ),
        )


def validate_report_status(status: str) -> None:
    """Reject unknown status filters (HTTP 422)."""
    if status not in REPORT_STATUSES:
        raise HTTPException(
            status_code=422,
            detail=(
                f"unknown status {status!r}; "
                f"expected one of {', '.join(REPORT_STATUSES)}"
            ),
        )


def default_report_name(report_type: str, reporting_year: int) -> str:
    """Derive a display name from real report metadata (never fabricated)."""
    label = {
        "annual": "Annual emissions report",
    }.get(report_type, report_type.replace("_", " ").title())
    return f"{label} {reporting_year}"


def shape_report_status(report: dict) -> dict:
    """Attach the display label and ready flag for the dashboard.

    ``ready`` is derived from the persisted row state only: the report must be
    ``completed`` and carry persisted content/artefact details.
    """
    status = report.get("status") or "pending"
    content = report.get("generated_content") or {}
    ready = (
        status == "completed"
        and bool(content)
        and (bool(report.get("final_report_url")) or bool(report.get("page_count")))
    )
    return {
        **report,
        "status_label": STATUS_LABELS.get(status, status),
        "ready": ready,
    }


def shape_report_out(report: dict, current_version: Optional[dict] = None) -> dict:
    """Shape the API-facing report detail (lifecycle + provenance + version)."""
    shaped = shape_report_status(report)
    shaped["current_version"] = current_version or {}
    shaped["reporting_period"] = {
        "start_date": f"{report['reporting_year']}-01-01",
        "end_date": f"{report['reporting_year']}-12-31",
        "reporting_year": report["reporting_year"],
    }
    return shaped


# ---------------------------------------------------------------------------
# Surfaces
# ---------------------------------------------------------------------------


@router.get("/types")
async def report_types(
    current_user: AuthUser = Depends(require_org_member()),
) -> dict:
    """Report types the V3 engine can actually produce (no invented types)."""
    return {
        "report_types": [
            {"id": type_id, "name": name}
            for type_id, name in SUPPORTED_REPORT_TYPES.items()
        ]
    }


@router.get("")
async def list_reports(
    organization_id: str = Query(..., min_length=1),
    status: Optional[str] = Query(None),
    report_type: Optional[str] = Query(None),
    reporting_year: Optional[int] = Query(None, ge=1990, le=2100),
    limit: int = Query(100, ge=1, le=500),
    offset: int = Query(0, ge=0),
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """List report rows for the organisation (real persisted data only)."""
    ensure_org_access(current_user, organization_id)
    if status is not None:
        validate_report_status(status)
    if report_type is not None:
        validate_report_type(report_type)
    reports = await repos.reports.list_full(
        organization_id,
        status=status,
        report_type=report_type,
        reporting_year=reporting_year,
        limit=limit,
        offset=offset,
    )
    return {
        "reports": [shape_report_status(r) for r in reports],
        "count_by_status": await repos.reports.count_by_status(organization_id),
        # D21.7: authoritative presentation brand for this report surface —
        # CarbonTally for Direct Customers / staff; the caller's OWN firm only
        # when the caller is a consultant with an ACTIVE grant (D15) for the
        # organisation. Never derived from client-supplied ids.
        "branding": (
            await resolve_report_branding(repos, current_user, organization_id)
        ).to_dict(),
    }


@router.post("", status_code=201)
async def generate_report(
    payload: ReportGenerateIn,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
    engine: ReportGenerationEngine = Depends(get_report_engine),
) -> dict:
    """Generate a report through the authoritative engine (synchronous).

    Lifecycle: QUEUED → GENERATING → READY (``completed``), or → FAILED with
    the real ``error_log`` persisted. On success a version snapshot is recorded
    on the existing ``report_versions`` table.
    """
    ensure_org_access(current_user, payload.organization_id)
    validate_report_type(payload.report_type)

    # QUEUED — create the queue row first so every lifecycle state is persisted.
    request_row = await repos.reports.create_generation_request(
        payload.organization_id,
        payload.report_type,
        payload.reporting_year,
        payload.template_id,
        created_by=current_user.user_id,
        report_name=default_report_name(payload.report_type, payload.reporting_year),
    )
    request = ReportRequest(
        organization_id=payload.organization_id,
        report_type=payload.report_type,
        reporting_year=payload.reporting_year,
        template_id=payload.template_id,
        options=dict(payload.options or {}),
    )

    try:
        # GENERATING (transient, synchronous request).
        await repos.reports.mark_generating(request_row.id, user_id=current_user.user_id)
        result = await engine.generate(request, report_id=request_row.id)
    except HTTPException:
        raise
    except Exception as exc:  # noqa: BLE001 - persist the real failure, then re-raise
        await repos.reports.mark_failed(
            request_row.id,
            error_log=str(exc),
            user_id=current_user.user_id,
        )
        status_code = getattr(exc, "http_status", 500)
        detail = getattr(exc, "message", None) or str(exc)
        raise HTTPException(status_code=status_code, detail=detail) from exc
        # NOTE: the CarbonTally error ``code`` is not echoed to keep the
        # response contract consistent with the router's error mapping.

    content = result.content.to_dict()
    # READY — record a version snapshot on the existing report_versions table.
    version = await repos.report_versions.create(
        report_id=result.report.id,
        version_number=await repos.report_versions.next_version_number(result.report.id),
        content=content,
        file_url=result.report.storage_url,
        file_name=f"report-{result.report.id}.json",
        created_by=current_user.user_id,
        change_summary=(
            f"Generated {payload.report_type} report for "
            f"{payload.reporting_year} by {current_user.user_id}"
        ),
        is_current=True,
    )
    full = await repos.reports.get_full(result.report.id)
    if full is None:  # pragma: no cover - row was just completed
        raise HTTPException(status_code=500, detail="report not found after generation")
    return {"report": shape_report_out(full, version), "content": content}


@router.get("/{report_id}")
async def get_report(
    report_id: str,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Report detail: lifecycle, provenance, current version (org-isolated)."""
    report = await repos.reports.get_full(report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    ensure_org_access(current_user, report["organization_id"])
    current_version = await repos.report_versions.get_current(report_id)
    return {
        "report": shape_report_out(report, current_version),
        # D21.7: authoritative presentation brand for this report surface.
        "branding": (
            await resolve_report_branding(
                repos, current_user, report["organization_id"]
            )
        ).to_dict(),
    }


@router.get("/{report_id}/content")
async def get_report_content(
    report_id: str,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Structured report content for preview (only when READY, real data)."""
    report = await repos.reports.get_full(report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    ensure_org_access(current_user, report["organization_id"])
    if report["status"] != "completed":
        raise HTTPException(
            status_code=409,
            detail=f"report is not ready (status={report['status']})",
        )
    content = report.get("generated_content") or {}
    if not content:
        raise HTTPException(status_code=404, detail="report has no generated content")
    return {"report_id": report_id, "content": content}


@router.get("/{report_id}/versions")
async def list_report_versions(
    report_id: str,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Version history for a report (existing ``report_versions`` table)."""
    report = await repos.reports.get_full(report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    ensure_org_access(current_user, report["organization_id"])
    return {
        "report_id": report_id,
        "versions": await repos.report_versions.list_for_report(report_id),
    }


@router.get("/{report_id}/download")
async def download_report(
    report_id: str,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> JSONResponse:
    """Secure download of the persisted report content (org-isolated).

    The report artefact is the structured ``generated_content`` JSONB written
    by the engine (no PDF rendering exists in V3 — documented backend gap). The
    content is served as a JSON attachment through the authenticated API only;
    no public storage URL is created.
    """
    report = await repos.reports.get_full(report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    ensure_org_access(current_user, report["organization_id"])
    if report["status"] != "completed":
        raise HTTPException(
            status_code=409,
            detail=f"report is not ready (status={report['status']})",
        )
    content = report.get("generated_content") or {}
    if not content:
        raise HTTPException(status_code=404, detail="report has no generated content")
    payload = {
        "report_id": report_id,
        "organization_id": report["organization_id"],
        "report_type": report["report_type"],
        "reporting_year": report["reporting_year"],
        "status": "completed",
        "generated_at": report["completed_at"] or report["updated_at"],
        "content": content,
        # D21/D25: server-authorized presentation brand for this report
        # (CarbonTally / Consultant / Co-branded) so any downstream renderer
        # NEVER trusts a client-supplied consultant_id or brand input.
        "branding": (
            await resolve_report_branding(repos, current_user, report["organization_id"])
        ).to_dict(),
    }
    filename = report.get("final_report_file_name") or f"report-{report_id}.json"
    filename = report.get("final_report_file_name") or f"report-{report_id}.json"
    return JSONResponse(
        content=payload,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/{report_id}/pdf")
async def download_report_pdf(
    report_id: str,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> Response:
    """White-label PDF rendering (D27 / D19 §18).

    The PDF is rendered from the persisted structured report content plus the
    SERVER-authorized brand context (CarbonTally / consultant / co-branded).
    The brand is resolved from the authenticated relationship — a client-
    supplied brand is never accepted.
    """
    report = await repos.reports.get_full(report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    ensure_org_access(current_user, report["organization_id"])
    if report["status"] != "completed":
        raise HTTPException(
            status_code=409,
            detail=f"report is not ready (status={report['status']})",
        )
    content = report.get("generated_content") or {}
    if not content:
        raise HTTPException(status_code=404, detail="report has no generated content")
    brand = await resolve_report_branding(
        repos, current_user, report["organization_id"]
    )
    try:
        pdf_bytes = render_branded_pdf(
            report={
                "report_type": report.get("report_type"),
                "reporting_year": report.get("reporting_year"),
            },
            content=content,
            brand=brand,
        )
    except Exception as exc:  # noqa: BLE001 — never leak renderer internals
        raise HTTPException(
            status_code=500, detail=f"report PDF rendering failed: {type(exc).__name__}"
        )
    filename = f"report-{report_id}-{brand.kind}.pdf"
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
    return JSONResponse(
        content=payload,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
