"""V3 reports surface (V3 Phase 5).

The org-scoped reporting workflow built on the authoritative chain:

    Source → Extraction → Mapping → Factor matching → Calculation engine
        → Validation → Review → Approval → REPORT

Reports are generated by the authoritative ``ReportGenerationEngine`` (the
same engine behind ``POST /api/v2/generate-report``) from the persisted
``emissions_logs`` / ``calculation_snapshots`` data. The frontend never
calculates or fabricates content; every response below reads the persisted
``report_generation_queue`` row (lifecycle, provenance, artefact state) and the
``generated_content`` JSONB written by the engine.

Lifecycle (preserving the existing synchronous architecture — no worker
infrastructure)::

    QUEUED (pending) → GENERATING (transient) → READY (completed)
    QUEUED (pending) → GENERATING (transient) → FAILED (failed + error_log)

Generation is synchronous inside the request: the queue row is created first
(QUEUED), moved to ``generating``, then the engine completes it (READY). On any
failure the real error is persisted to ``error_log`` and the row is marked
``failed`` — nothing is presented as ready unless the backend confirms the row
is ``completed`` with persisted content.

Versioning reuses the existing ``report_versions`` table (V3M2 schema): a
snapshot row is recorded on every successful generation.

The report **version lifecycle** (Phase 8 S3) is version-scoped on that same
table: ``status`` moves ``DRAFT`` → ``REVIEWED`` → ``APPROVED`` → ``FINAL``
under server-side guards, with ``CHANGES_REQUESTED`` / ``REJECTED`` review
outcomes, append-only audit events on the canonical ``audit_trail``, and
supersession by a new ``DRAFT`` version after approval/finalisation (an
approved/final version is never mutated). Approval is the customer
organisation's own assertion — never independent GHG assurance or verification.

Export reuses the existing org-isolated ``/api/v3/exports/*`` surface (CSV/JSON)
— no second export implementation.
"""
from __future__ import annotations

import uuid
from datetime import date, datetime, time, timezone
from typing import Any, Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, ConfigDict, Field

from api.consultant_branding import resolve_report_branding
from api.dependencies import (
    RepositoryBundle,
    ensure_org_access,
    get_report_engine,
    get_repositories,
    require_org_member,
)
from auth import AuthUser
from core.logging import get_logger
from domain.audit import (
    ACTOR_ORG_USER,
    CAT_REPORT,
    ORIGIN_HUMAN,
    OUTCOME_SUCCESS,
    AuditEntry,
)
from domain.report import ReportRequest
from domain.report_lifecycle import (
    APPROVE,
    AUDIT_EVENTS,
    AUTHORITY_ADMIN,
    DEFAULT_STATUS,
    FINALIZE,
    NEW_VERSION,
    REJECT,
    REQUEST_CHANGES,
    SUBMIT,
    TransitionNotAllowed,
    allowed_actions,
    can_create_new_version,
    required_authority,
    resolve_transition,
)
from engines.pdf_render import render_branded_pdf
from engines.report_generation import ReportGenerationEngine
from services.report_schedules import (
    ReportScheduleService,
    ScheduleInUseError,
    ScheduleValidationError,
    canonical_frequencies,
    shape_run as shape_scheduled_run,
    shape_schedule,
)
from services.report_shares import (
    ReportShareService,
    ShareConflictError,
    ShareNotShareableError,
    ShareValidationError,
    shape_event as shape_share_event,
    shape_share,
)

logger = get_logger(__name__)

router = APIRouter(prefix="/api/v3/reports", tags=["V3 — Reports"])

#: Report types the V3 engine genuinely supports. The engine composes one
#: structured 12-section report (annual emissions) from the persisted logs;
#: the legacy generator's other labels (summary/documents/staff/...) have no V3
#: engine backing and are deliberately not offered.
SUPPORTED_REPORT_TYPES: dict[str, str] = {
    "annual": "Annual emissions report (structured 12-section V3 report)",
}

#: Queue statuses surfaced by the dashboard (persisted values on the existing
#: ``report_generation_queue.status`` column).
REPORT_STATUSES: tuple[str, ...] = ("pending", "generating", "completed", "failed")

#: Human-readable display labels for persisted statuses.
STATUS_LABELS: dict[str, str] = {
    "pending": "Queued",
    "generating": "Generating",
    "completed": "Ready",
    "failed": "Failed",
}


class ReportGenerateIn(BaseModel):
    """Request to generate a report (client never supplies the result)."""

    organization_id: str = Field(..., min_length=1)
    report_type: str = "annual"
    reporting_year: int = Field(..., ge=1990, le=2100)
    template_id: Optional[str] = None
    options: dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(extra="forbid")


# ---------------------------------------------------------------------------
# Helpers (pure — unit-tested without a database)
# ---------------------------------------------------------------------------


def validate_report_type(report_type: str) -> None:
    """Reject report types with no V3 engine/data backing (HTTP 422)."""
    if report_type not in SUPPORTED_REPORT_TYPES:
        raise HTTPException(
            status_code=422,
            detail=(
                f"unsupported report type {report_type!r}; "
                f"supported: {', '.join(sorted(SUPPORTED_REPORT_TYPES))}"
            ),
        )


def validate_report_status(status: str) -> None:
    """Reject unknown status filters (HTTP 422)."""
    if status not in REPORT_STATUSES:
        raise HTTPException(
            status_code=422,
            detail=(
                f"unknown status {status!r}; "
                f"expected one of {', '.join(REPORT_STATUSES)}"
            ),
        )


def default_report_name(report_type: str, reporting_year: int) -> str:
    """Derive a display name from real report metadata (never fabricated)."""
    label = {
        "annual": "Annual emissions report",
    }.get(report_type, report_type.replace("_", " ").title())
    return f"{label} {reporting_year}"


def shape_report_status(report: dict) -> dict:
    """Attach the display label and ready flag for the dashboard.

    ``ready`` is derived from the persisted row state only: the report must be
    ``completed`` and carry persisted content/artefact details.
    """
    status = report.get("status") or "pending"
    content = report.get("generated_content") or {}
    ready = (
        status == "completed"
        and bool(content)
        and (bool(report.get("final_report_url")) or bool(report.get("page_count")))
    )
    return {
        **report,
        "status_label": STATUS_LABELS.get(status, status),
        "ready": ready,
    }


def shape_report_out(report: dict, current_version: Optional[dict] = None) -> dict:
    """Shape the API-facing report detail (lifecycle + provenance + version)."""
    shaped = shape_report_status(report)
    shaped["current_version"] = current_version or {}
    shaped["reporting_period"] = {
        "start_date": f"{report['reporting_year']}-01-01",
        "end_date": f"{report['reporting_year']}-12-31",
        "reporting_year": report["reporting_year"],
    }
    return shaped


def shape_report_list_row(
    report: dict, current_version: Optional[dict] = None
) -> dict:
    """Shape one report-listing row, exposing the real current version (S1-B).

    The listing contract is the dashboard row plus ``current_version``; unlike
    :func:`shape_report_out` it deliberately does **not** add the detail-only
    ``reporting_period``. ``current_version`` is the persisted current version
    (authoritative ``report_versions.is_current``) or ``{}`` when the report has
    none — absence is never presented as version 1.
    """
    shaped = shape_report_status(report)
    shaped["current_version"] = current_version or {}
    return shaped


# ---------------------------------------------------------------------------
# Surfaces
# ---------------------------------------------------------------------------


@router.get("/types")
async def report_types(
    current_user: AuthUser = Depends(require_org_member()),
) -> dict:
    """Report types the V3 engine can actually produce (no invented types)."""
    return {
        "report_types": [
            {"id": type_id, "name": name}
            for type_id, name in SUPPORTED_REPORT_TYPES.items()
        ]
    }


@router.get("")
async def list_reports(
    organization_id: str = Query(..., min_length=1),
    status: Optional[str] = Query(None),
    report_type: Optional[str] = Query(None),
    reporting_year: Optional[int] = Query(None, ge=1990, le=2100),
    limit: int = Query(100, ge=1, le=500),
    offset: int = Query(0, ge=0),
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """List report rows for the organisation (real persisted data only)."""
    ensure_org_access(current_user, organization_id)
    if status is not None:
        validate_report_status(status)
    if report_type is not None:
        validate_report_type(report_type)
    reports = await repos.reports.list_full(
        organization_id,
        status=status,
        report_type=report_type,
        reporting_year=reporting_year,
        limit=limit,
        offset=offset,
    )
    # S1-B: expose the real current version for the listed reports in ONE
    # batched query (no N+1). Sourced from ``report_versions.is_current`` — not
    # from row counts and not from MAX(version_number). A report with no current
    # version yields ``{}`` rather than a fabricated version 1.
    current_versions = await repos.report_versions.current_by_reports(
        [r["id"] for r in reports]
    )
    return {
        "reports": [
            shape_report_list_row(r, current_versions.get(r["id"])) for r in reports
        ],
        "count_by_status": await repos.reports.count_by_status(organization_id),
        # D21.7: authoritative presentation brand for this report surface —
        # CarbonTally for Direct Customers / staff; the caller's OWN firm only
        # when the caller is a consultant with an ACTIVE grant (D15) for the
        # organisation. Never derived from client-supplied ids.
        "branding": (
            await resolve_report_branding(repos, current_user, organization_id)
        ).to_dict(),
    }


@router.post("", status_code=201)
async def generate_report(
    payload: ReportGenerateIn,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
    engine: ReportGenerationEngine = Depends(get_report_engine),
) -> dict:
    """Generate a report through the authoritative engine (synchronous).

    Lifecycle: QUEUED → GENERATING → READY (``completed``), or → FAILED with
    the real ``error_log`` persisted. On success a version snapshot is recorded
    on the existing ``report_versions`` table.
    """
    ensure_org_access(current_user, payload.organization_id)
    validate_report_type(payload.report_type)

    # QUEUED — create the queue row first so every lifecycle state is persisted.
    request_row = await repos.reports.create_generation_request(
        payload.organization_id,
        payload.report_type,
        payload.reporting_year,
        payload.template_id,
        created_by=current_user.user_id,
        report_name=default_report_name(payload.report_type, payload.reporting_year),
    )
    request = ReportRequest(
        organization_id=payload.organization_id,
        report_type=payload.report_type,
        reporting_year=payload.reporting_year,
        template_id=payload.template_id,
        options=dict(payload.options or {}),
    )

    try:
        # GENERATING (transient, synchronous request).
        await repos.reports.mark_generating(request_row.id, user_id=current_user.user_id)
        result = await engine.generate(request, report_id=request_row.id)
    except HTTPException:
        raise
    except Exception as exc:  # noqa: BLE001 - persist the real failure, then re-raise
        await repos.reports.mark_failed(
            request_row.id,
            error_log=str(exc),
            user_id=current_user.user_id,
        )
        status_code = getattr(exc, "http_status", 500)
        detail = getattr(exc, "message", None) or str(exc)
        raise HTTPException(status_code=status_code, detail=detail) from exc
        # NOTE: the CarbonTally error ``code`` is not echoed to keep the
        # response contract consistent with the router's error mapping.

    content = result.content.to_dict()
    # READY — record a version snapshot on the existing report_versions table.
    version = await repos.report_versions.create(
        report_id=result.report.id,
        version_number=await repos.report_versions.next_version_number(result.report.id),
        content=content,
        file_url=result.report.storage_url,
        file_name=f"report-{result.report.id}.json",
        created_by=current_user.user_id,
        change_summary=(
            f"Generated {payload.report_type} report for "
            f"{payload.reporting_year} by {current_user.user_id}"
        ),
        is_current=True,
    )
    full = await repos.reports.get_full(result.report.id)
    if full is None:  # pragma: no cover - row was just completed
        raise HTTPException(status_code=500, detail="report not found after generation")
    return {"report": shape_report_out(full, version), "content": content}


# ---------------------------------------------------------------------------
# CT-IMPLEMENT-03 — canonical scheduled reporting (PD-2)
# ---------------------------------------------------------------------------
# Ratified PO decision PD-2 implements scheduled reporting; the schema is
# ``supabase/migrations/20261023000000_ct02_scheduled_reporting.sql``
# (``report_schedule_definitions`` + ``report_schedule_runs``), the vocabulary is
# ``domain.report_schedule``, and execution is
# ``services.report_schedule_runner`` (driven by ``workers.report_schedules``).
#
# These routes are the application surface for that model. They create, list,
# pause, resume and delete *canonical* schedules and read their real execution
# history. The retired ``report_schedules`` table is not referenced anywhere on
# this path and must never be reintroduced (PD-2).
#
# Authority: reading a schedule is an organisation-member action; creating,
# pausing, resuming or deleting one is an organisation-AUTHORITY action
# (owner/admin), matching the RLS policies the schema declares for the table.
# ---------------------------------------------------------------------------


class ScheduleCreateIn(BaseModel):
    """Request to create a canonical report schedule."""

    organization_id: str = Field(..., min_length=1)
    name: str = Field(..., min_length=1, max_length=200)
    report_type: str = "annual"
    reporting_year: int = Field(..., ge=1990, le=2100)
    frequency: str = Field(..., min_length=1)
    run_time: time = time(7, 0)
    timezone: str = "Europe/London"
    recipients: list[str] = Field(..., min_length=1)
    period_start: Optional[date] = None
    period_end: Optional[date] = None
    retry_policy: Optional[dict[str, Any]] = None
    is_active: bool = True

    model_config = ConfigDict(extra="forbid")


def authorize_org_authority(
    current_user: AuthUser, organization_id: str, action: str
) -> None:
    """Require organisation owner/admin authority for ``action``, server-side.

    Mirrors the schema's own RLS authority for the schedule/share tables
    (``p8_disclosure_is_org_admin``): Processing Entity staff and CarbonTally
    internal staff are not customer-organisation authorities, a read-only
    ``viewer`` is not an authority, and a member of another organisation is
    refused by :func:`ensure_org_access`. The UI is never the boundary.
    """
    if current_user.is_entity_staff:
        raise HTTPException(
            status_code=403,
            detail="Processing Entity staff cannot manage customer report schedules",
        )
    if current_user.is_internal_staff:
        raise HTTPException(
            status_code=403,
            detail=(
                "CarbonTally staff cannot act as a customer organisation authority"
            ),
        )
    ensure_org_access(current_user, organization_id)
    if _org_role(current_user) not in _ORG_AUTHORITY_ROLES:
        raise HTTPException(
            status_code=403,
            detail=f"action {action!r} requires organisation owner/admin access",
        )


def authorize_org_member(
    current_user: AuthUser, organization_id: str, action: str
) -> None:
    """Require at least organisation-member access for a read-only ``action``."""
    if current_user.is_entity_staff:
        raise HTTPException(
            status_code=403,
            detail="Processing Entity staff cannot read customer report schedules",
        )
    ensure_org_access(current_user, organization_id)


def _schedule_error(exc: ScheduleValidationError) -> HTTPException:
    """Map a canonical schedule-validation failure to a described 4xx.

    A schedule that has executed cannot be deleted (its run history is immutable),
    which is a conflict with the current state rather than a bad request, so it is
    reported as 409 with the same described body.
    """
    detail = {"message": str(exc), "field": exc.field or "schedule"}
    if isinstance(exc, ScheduleInUseError):
        return HTTPException(status_code=409, detail=detail)
    return HTTPException(status_code=422, detail=detail)


def _share_error(exc: Exception) -> HTTPException:
    """Map a share-domain failure to its correct status (never a 500)."""
    if isinstance(exc, ShareNotShareableError):
        return HTTPException(
            status_code=409,
            detail={"message": str(exc), "field": exc.field or "version_number"},
        )
    if isinstance(exc, ShareConflictError):
        return HTTPException(
            status_code=409, detail={"message": str(exc), "field": "recipients"}
        )
    if isinstance(exc, ShareValidationError):
        return HTTPException(
            status_code=422,
            detail={"message": str(exc), "field": exc.field or "share"},
        )
    return HTTPException(status_code=500, detail="Unable to complete the share request")


@router.get("/schedules/frequencies")
async def list_schedule_frequencies(
    current_user: AuthUser = Depends(require_org_member()),
) -> dict:
    """The canonical frequency vocabulary (exactly what the database accepts).

    Declared before ``/schedules/{schedule_id}`` so the literal path wins. This
    is the same list the retired ``/api/reports/schedule/frequencies`` surface now
    returns, so no caller can be told a frequency the schema rejects (F-2).
    """
    return {"frequencies": canonical_frequencies()}


@router.post("/schedules", status_code=201)
async def create_schedule(
    payload: ScheduleCreateIn,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Create a canonical report schedule (organisation authority required)."""
    authorize_org_authority(current_user, payload.organization_id, "create_schedule")
    service = ReportScheduleService(repos)
    try:
        schedule = await service.create(
            payload.organization_id,
            actor=current_user.user_id,
            name=payload.name,
            report_type=payload.report_type,
            reporting_year=payload.reporting_year,
            frequency=payload.frequency,
            run_time=payload.run_time,
            recipients=payload.recipients,
            timezone_name=payload.timezone,
            period_start=payload.period_start,
            period_end=payload.period_end,
            retry_policy=payload.retry_policy,
            is_active=payload.is_active,
        )
    except ScheduleValidationError as exc:
        raise _schedule_error(exc) from exc
    return {"schedule": shape_schedule(schedule)}


@router.get("/schedules")
async def list_schedules(
    organization_id: str = Query(..., min_length=1),
    is_active: Optional[bool] = Query(default=None),
    limit: int = Query(default=100, ge=1, le=500),
    offset: int = Query(default=0, ge=0),
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """List an organisation's schedules with their persisted execution state."""
    authorize_org_member(current_user, organization_id, "list_schedules")
    page = await ReportScheduleService(repos).list_schedules(
        organization_id, is_active=is_active, limit=limit, offset=offset
    )
    return {
        **{k: v for k, v in page.items() if k != "schedules"},
        "schedules": [shape_schedule(item) for item in page["schedules"]],
    }


@router.get("/schedules/{schedule_id}")
async def get_schedule(
    schedule_id: str,
    organization_id: str = Query(..., min_length=1),
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """One schedule plus its real execution history (no fabricated outcomes)."""
    authorize_org_member(current_user, organization_id, "get_schedule")
    service = ReportScheduleService(repos)
    schedule = await service.get(organization_id, schedule_id)
    if schedule is None:
        raise HTTPException(status_code=404, detail="report schedule not found")
    runs = await service.runs(organization_id, schedule_id, limit=20) or []
    return {
        "schedule": shape_schedule(schedule),
        "runs": [shape_scheduled_run(run) for run in runs],
    }


@router.get("/schedules/{schedule_id}/runs")
async def list_schedule_runs(
    schedule_id: str,
    organization_id: str = Query(..., min_length=1),
    limit: int = Query(default=50, ge=1, le=200),
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Execution history for one schedule (idempotent slots, real outcomes)."""
    authorize_org_member(current_user, organization_id, "list_schedule_runs")
    runs = await ReportScheduleService(repos).runs(
        organization_id, schedule_id, limit=limit
    )
    if runs is None:
        raise HTTPException(status_code=404, detail="report schedule not found")
    return {"schedule_id": schedule_id, "runs": [shape_scheduled_run(r) for r in runs]}


@router.post("/schedules/{schedule_id}/pause")
async def pause_schedule(
    schedule_id: str,
    organization_id: str = Query(..., min_length=1),
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Pause a schedule (``is_active = false`` + ``paused_at``), audited."""
    authorize_org_authority(current_user, organization_id, "pause_schedule")
    row = await ReportScheduleService(repos).pause(
        organization_id, schedule_id, actor=current_user.user_id
    )
    if row is None:
        raise HTTPException(status_code=404, detail="report schedule not found")
    return {"schedule": shape_schedule(row)}


@router.post("/schedules/{schedule_id}/resume")
async def resume_schedule(
    schedule_id: str,
    organization_id: str = Query(..., min_length=1),
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Resume a paused schedule and re-establish a real due time, audited."""
    authorize_org_authority(current_user, organization_id, "resume_schedule")
    row = await ReportScheduleService(repos).resume(
        organization_id, schedule_id, actor=current_user.user_id
    )
    if row is None:
        raise HTTPException(status_code=404, detail="report schedule not found")
    return {"schedule": shape_schedule(row)}


@router.delete("/schedules/{schedule_id}")
async def delete_schedule(
    schedule_id: str,
    organization_id: str = Query(..., min_length=1),
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Delete a schedule (audited); its run history cascades with it."""
    authorize_org_authority(current_user, organization_id, "delete_schedule")
    try:
        deleted = await ReportScheduleService(repos).delete(
            organization_id, schedule_id, actor=current_user.user_id
        )
    except ScheduleValidationError as exc:
        raise _schedule_error(exc) from exc
    if not deleted:
        raise HTTPException(status_code=404, detail="report schedule not found")
    return {"schedule_id": schedule_id, "deleted": True}


# ---------------------------------------------------------------------------
# CT-IMPLEMENT-03 — canonical report sharing (PD-1)
# ---------------------------------------------------------------------------
# Ratified PO decision PD-1 implements report sharing against the canonical
# report/version architecture. The schema is
# ``supabase/migrations/20261022000000_ct02_report_sharing.sql``
# (``report_shares`` + ``report_share_access_events``), and the rules are the
# schema's own: a share is bound to ONE immutable (APPROVED/FINAL) version, names
# an explicit recipient, is tenant-owned, may expire, is revoked (never erased)
# with a reason, and keeps an append-only access history.
#
# Sharing is a version-scoped act on a report, so ``POST /{report_id}/shares``
# without ``version_number`` binds to the report's CURRENT version. That is the
# only reading consistent with the canonical model: PD-1 sharing is version-bound,
# so "share this report" can only mean "share its current version", and a report
# whose current version is still mutable is refused (409) rather than shared.
#
# NOT implemented here (PO-gated in the CT-IMPLEMENT-03 report, G-2): consuming a
# share — returning the report content to a recipient and recording
# ``access``/``download``/``denied`` events. That needs a delivery/download policy
# decision and signed-URL handling; no policy has been invented in its place.
# ---------------------------------------------------------------------------


class ShareCreateIn(BaseModel):
    """Request to share one version of a report with explicit recipients."""

    organization_id: str = Field(..., min_length=1)
    recipients: list[str] = Field(..., min_length=1)
    permission: str = "view"
    version_number: Optional[int] = Field(default=None, ge=1)
    expires_at: Optional[datetime] = None

    model_config = ConfigDict(extra="forbid")


class ShareRevokeIn(BaseModel):
    """Request to revoke one share (self-describing, per the schema)."""

    organization_id: str = Field(..., min_length=1)
    reason: str = Field(..., min_length=1, max_length=500)

    model_config = ConfigDict(extra="forbid")


@router.post("/{report_id}/shares", status_code=201)
async def create_report_share(
    report_id: str,
    payload: ShareCreateIn,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Share one immutable version of a report (organisation authority required)."""
    authorize_org_authority(current_user, payload.organization_id, "share_report")
    service = ReportShareService(repos)
    try:
        shares = await service.share(
            organization_id=payload.organization_id,
            report_id=report_id,
            actor=current_user.user_id,
            recipients=payload.recipients,
            permission=payload.permission,
            version_number=payload.version_number,
            expires_at=payload.expires_at,
        )
    except (ShareValidationError, ShareConflictError) as exc:
        raise _share_error(exc) from exc
    return {
        "report_id": report_id,
        "shared": [shape_share(row) for row in shares],
        "count": len(shares),
    }


@router.get("/{report_id}/shares")
async def list_report_shares(
    report_id: str,
    organization_id: str = Query(..., min_length=1),
    include_revoked: bool = Query(default=True),
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """The share register of one report (revoked history included by default)."""
    authorize_org_member(current_user, organization_id, "list_report_shares")
    report = await repos.reports.get_full(report_id)
    if report is None or str(report["organization_id"]) != str(organization_id):
        raise HTTPException(status_code=404, detail="report not found")
    shares = await ReportShareService(repos).list_for_report(
        report_id, include_revoked=include_revoked
    )
    return {"report_id": report_id, "shares": [shape_share(row) for row in shares]}


@router.post("/shares/{share_id}/revoke")
async def revoke_report_share(
    share_id: str,
    payload: ShareRevokeIn,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Revoke a share (reason required); the register keeps the history."""
    authorize_org_authority(current_user, payload.organization_id, "revoke_share")
    service = ReportShareService(repos)
    try:
        row = await service.revoke(
            org_scope=payload.organization_id,
            share_id=share_id,
            actor=current_user.user_id,
            reason=payload.reason,
        )
    except ShareValidationError as exc:
        raise _share_error(exc) from exc
    if row is None:
        raise HTTPException(status_code=404, detail="report share not found")
    return {"share": shape_share(row)}


@router.get("/shares/{share_id}/access-history")
async def get_share_access_history(
    share_id: str,
    organization_id: str = Query(..., min_length=1),
    limit: int = Query(default=100, ge=1, le=500),
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Append-only access/revocation history for one share."""
    authorize_org_member(current_user, organization_id, "share_access_history")
    share = await repos.report_shares.get_for_org(share_id, organization_id)
    if share is None:
        raise HTTPException(status_code=404, detail="report share not found")
    events = await ReportShareService(repos).access_history(share_id, limit=limit) or []
    return {
        "share_id": share_id,
        "share": shape_share(share),
        "events": [shape_share_event(event) for event in events],
    }


@router.get("/shares/received")
async def list_received_shares(
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Reports shared with the calling user (live, unexpired shares only).

    The recipient may belong to another organisation, so this read is scoped to
    the caller's own identity rather than to an organisation — exactly the read
    predicate the schema's RLS policy grants a recipient.
    """
    shares = await ReportShareService(repos).received(
        user_id=current_user.user_id, email=current_user.email
    )
    return {"shares": [shape_share(row) for row in shares]}


@router.get("/{report_id}")
async def get_report(
    report_id: str,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Report detail: lifecycle, provenance, current version (org-isolated)."""
    report = await repos.reports.get_full(report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    ensure_org_access(current_user, report["organization_id"])
    current_version = await repos.report_versions.get_current(report_id)
    return {
        "report": shape_report_out(report, current_version),
        # D21.7: authoritative presentation brand for this report surface.
        "branding": (
            await resolve_report_branding(
                repos, current_user, report["organization_id"]
            )
        ).to_dict(),
    }


@router.get("/{report_id}/content")
async def get_report_content(
    report_id: str,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Structured report content for preview (only when READY, real data)."""
    report = await repos.reports.get_full(report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    ensure_org_access(current_user, report["organization_id"])
    if report["status"] != "completed":
        raise HTTPException(
            status_code=409,
            detail=f"report is not ready (status={report['status']})",
        )
    content = report.get("generated_content") or {}
    if not content:
        raise HTTPException(status_code=404, detail="report has no generated content")
    return {"report_id": report_id, "content": content}


@router.get("/{report_id}/versions")
async def list_report_versions(
    report_id: str,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """Version history for a report (existing ``report_versions`` table).

    S6 — each version row carries ``allowed_actions`` for its **persisted**
    status. The UI renders lifecycle controls from this server-authoritative
    set rather than deriving them, so the displayed state can never conflict
    with the lifecycle state machine. This is additive and read-only.
    """
    report = await repos.reports.get_full(report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    ensure_org_access(current_user, report["organization_id"])
    versions = await repos.report_versions.list_for_report(report_id)
    return {
        "report_id": report_id,
        "versions": [
            {
                **version,
                "allowed_actions": list(allowed_actions(version.get("status"))),
            }
            for version in versions
        ],
    }


@router.get("/{report_id}/download")
async def download_report(
    report_id: str,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> JSONResponse:
    """Secure download of the persisted report content (org-isolated).

    Serves the structured ``generated_content`` JSONB written by the engine as
    a JSON attachment through the authenticated API only — no public storage URL
    is created.

    This endpoint is the machine-readable JSON export. Branded PDF rendering is
    provided separately by ``GET /api/v3/reports/{report_id}/pdf``
    (``download_report_pdf`` → ``engines.pdf_render.render_branded_pdf``), which
    renders from this same persisted content plus the server-authorized brand.
    """
    report = await repos.reports.get_full(report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    ensure_org_access(current_user, report["organization_id"])
    if report["status"] != "completed":
        raise HTTPException(
            status_code=409,
            detail=f"report is not ready (status={report['status']})",
        )
    content = report.get("generated_content") or {}
    if not content:
        raise HTTPException(status_code=404, detail="report has no generated content")
    payload = {
        "report_id": report_id,
        "organization_id": report["organization_id"],
        "report_type": report["report_type"],
        "reporting_year": report["reporting_year"],
        "status": "completed",
        "generated_at": report["completed_at"] or report["updated_at"],
        "content": content,
        # D21/D25: server-authorized presentation brand for this report
        # (CarbonTally / Consultant / Co-branded) so any downstream renderer
        # NEVER trusts a client-supplied consultant_id or brand input.
        "branding": (
            await resolve_report_branding(repos, current_user, report["organization_id"])
        ).to_dict(),
    }
    filename = report.get("final_report_file_name") or f"report-{report_id}.json"
    filename = report.get("final_report_file_name") or f"report-{report_id}.json"
    return JSONResponse(
        content=payload,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/{report_id}/pdf")
async def download_report_pdf(
    report_id: str,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> Response:
    """White-label PDF rendering (D27 / D19 §18).

    The PDF is rendered from the persisted structured report content plus the
    SERVER-authorized brand context (CarbonTally / consultant / co-branded).
    The brand is resolved from the authenticated relationship — a client-
    supplied brand is never accepted.
    """
    report = await repos.reports.get_full(report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    ensure_org_access(current_user, report["organization_id"])
    if report["status"] != "completed":
        raise HTTPException(
            status_code=409,
            detail=f"report is not ready (status={report['status']})",
        )
    content = report.get("generated_content") or {}
    if not content:
        raise HTTPException(status_code=404, detail="report has no generated content")
    brand = await resolve_report_branding(
        repos, current_user, report["organization_id"]
    )
    try:
        pdf_bytes = render_branded_pdf(
            report={
                "report_type": report.get("report_type"),
                "reporting_year": report.get("reporting_year"),
            },
            content=content,
            brand=brand,
        )
    except Exception as exc:  # noqa: BLE001 — never leak renderer internals
        raise HTTPException(
            status_code=500, detail=f"report PDF rendering failed: {type(exc).__name__}"
        )
    filename = f"report-{report_id}-{brand.kind}.pdf"
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
    return JSONResponse(
        content=payload,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


# ---------------------------------------------------------------------------
# Phase 8 S3 — report VERSION lifecycle (state machine + audit + authorization)
# ---------------------------------------------------------------------------
# A report *instance* is ``report_generation_queue.id``; each *version* is a
# ``report_versions`` row. Lifecycle state is version-scoped and is deliberately
# separate from the generation status on the queue row. Approval is the
# customer's own assertion — it is never independent assurance or verification.
#
# Ratified boundary implemented here:
#   DRAFT → REVIEWED → APPROVED → FINAL, with REVIEWED → CHANGES_REQUESTED /
#   REJECTED review outcomes, and supersession by a NEW draft version after
#   approval/finalisation (the approved/final version itself is never mutated).
# ---------------------------------------------------------------------------

#: Organisation roles that may act on a report lifecycle (authoring/reviewing):
#: schema ``organization_members.role`` values plus the legacy ``user`` label
#: ``get_current_user`` uses for a non-staff account. Read-only roles (e.g.
#: ``viewer``) are deliberately absent, so no lifecycle action is possible for
#: them at either authority level.
_ORG_MEMBER_ROLES = frozenset({"owner", "admin", "member", "user"})
#: Organisation roles recognised as the organisation's authority (owner/admin),
#: mirroring the schema's RLS admin role set.
_ORG_AUTHORITY_ROLES = frozenset({"owner", "admin"})


class LifecycleTransitionIn(BaseModel):
    """Optional operator note recorded with a lifecycle transition."""

    note: Optional[str] = Field(default=None, max_length=2000)

    model_config = ConfigDict(extra="forbid")


class NewReportVersionIn(BaseModel):
    """Request to supersede one version with a new draft version."""

    from_version_number: int = Field(..., ge=1)
    reason: Optional[str] = Field(default=None, max_length=2000)

    model_config = ConfigDict(extra="forbid")


def _org_role(current_user: AuthUser) -> str:
    """Return the caller's organisation role, normalised.

    ``get_current_user`` derives ``role`` as ``org_<role>`` (e.g. ``org_owner``)
    while ``role_name`` carries the bare schema value (``owner``/``admin``).
    """
    role = (current_user.role_name or current_user.role or "").lower()
    if role.startswith("org_"):
        role = role[len("org_") :]
    return role



def _authorize_lifecycle_action(
    current_user: AuthUser, action: str, organization_id: str
) -> None:
    """Enforce the Phase 8 S3 lifecycle authorization boundary, server-side.

    * Organisation **Owner/Admin** are the organisation's authority — they may
      submit, request changes, reject, approve and finalize.
    * Any organisation **member** may submit a version for review and create a
      new version (the acting-org author).
    * A **Member/Viewer** may not request changes, reject, approve or finalize.
    * **Consultants**, **Processing Entities** and **CarbonTally internal staff**
      are never granted report-lifecycle authority in S3 (future, PO-gated
      decisions). The frontend is never the boundary.
    """
    if current_user.is_entity_staff:
        raise HTTPException(
            status_code=403,
            detail="Processing Entity staff cannot act on customer reports",
        )
    if current_user.is_internal_staff:
        raise HTTPException(
            status_code=403,
            detail="CarbonTally staff cannot perform report lifecycle transitions",
        )
    ensure_org_access(current_user, organization_id)
    role = _org_role(current_user)
    if required_authority(action) == AUTHORITY_ADMIN:
        permitted = role in _ORG_AUTHORITY_ROLES
        detail = f"action {action!r} requires organisation owner/admin access"
    else:
        permitted = role in _ORG_MEMBER_ROLES
        detail = f"action {action!r} requires organisation write access"
    if not permitted:
        raise HTTPException(status_code=403, detail=detail)


async def _record_lifecycle_event(
    repos: RepositoryBundle,
    *,
    action: str,
    actor: str,
    organization_id: str,
    report_id: str,
    version: dict,
    status_from: str,
    status_to: str,
    reason: Optional[str] = None,
    extra: Optional[dict[str, Any]] = None,
) -> None:
    """Append one lifecycle event to the canonical append-only ``audit_trail``.

    Reuses the existing audit substrate — no second ledger and no taxonomy
    change (the ``report`` action prefix already classifies to ``CAT_REPORT``).
    The event is version-scoped (``record_id`` = version id) and carries the
    from/to states, so the transition is reconstructable. Only field names and
    states are stored — never narrative bodies or document content. Best-effort:
    an audit failure must never break the already-persisted transition.
    """
    changed: dict[str, Any] = {
        "status_from": status_from,
        "status_to": status_to,
        "version_number": version["version_number"],
        "report_id": report_id,
    }
    if extra:
        changed.update(extra)
    entry = AuditEntry(
        id=str(uuid.uuid4()),
        correlation_id=report_id,
        entity_type="report_versions",
        entity_id=version["id"],
        action=AUDIT_EVENTS[action],
        actor=actor,
        occurred_at=datetime.now(timezone.utc),
        changed_fields=changed,
        reason=reason or "report version lifecycle transition",
        before={"status": status_from},
        after={"status": status_to},
        actor_type=ACTOR_ORG_USER,
        origin=ORIGIN_HUMAN,
        outcome=OUTCOME_SUCCESS,
        organization_id=organization_id,
        category=CAT_REPORT,
    )
    try:
        await repos.audit.record(entry)
    except Exception:  # noqa: BLE001 — audit must never break the transition
        logger.exception(
            "report lifecycle audit (%s) failed for version %s",
            AUDIT_EVENTS[action],
            version["id"],
        )



def shape_lifecycle_version(
    version: dict, *, action: str, status_from: str
) -> dict:
    """Deterministic lifecycle response body (version identity + new state)."""
    return {
        "version_id": version["id"],
        "version_number": version["version_number"],
        "status": version["status"],
        "status_from": status_from,
        "action": action,
        "is_current": version["is_current"],
        "allowed_actions": list(allowed_actions(version["status"])),
    }


async def _load_report_version(
    repos: RepositoryBundle,
    current_user: AuthUser,
    report_id: str,
    version_number: int,
) -> tuple[dict, dict]:
    """Load an org-scoped report and one specific version (404 when absent)."""
    report = await repos.reports.get_full(report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    ensure_org_access(current_user, report["organization_id"])
    version = await repos.report_versions.get_by_number(report_id, version_number)
    if version is None:
        raise HTTPException(status_code=404, detail="report version not found")
    return report, version


async def _apply_lifecycle_transition(
    repos: RepositoryBundle,
    current_user: AuthUser,
    report_id: str,
    version_number: int,
    action: str,
    note: Optional[str] = None,
) -> dict:
    """Apply one version-scoped lifecycle transition (guarded + audited).

    Order is deliberate: scope → authority → state-machine validation → atomic
    guarded persistence → audit. An invalid transition (``409``) or a lost
    concurrency race (``409``) never reaches the audit step, so no misleading
    success event is ever written.
    """
    report, version = await _load_report_version(
        repos, current_user, report_id, version_number
    )
    organization_id = report["organization_id"]
    _authorize_lifecycle_action(current_user, action, organization_id)

    status_from = version["status"]
    try:
        status_to = resolve_transition(action, status_from)
    except TransitionNotAllowed as exc:
        raise HTTPException(status_code=409, detail=str(exc)) from exc

    updated = await repos.report_versions.set_status(
        report_id=report_id,
        version_id=version["id"],
        expected_status=status_from,
        new_status=status_to,
    )
    if updated is None:
        current = await repos.report_versions.get_by_number(
            report_id, version_number
        )
        actual = current["status"] if current else "unknown"
        raise HTTPException(
            status_code=409,
            detail=f"report version state changed concurrently (now {actual})",
        )

    await _record_lifecycle_event(
        repos,
        action=action,
        actor=current_user.user_id,
        organization_id=organization_id,
        report_id=report_id,
        version=updated,
        status_from=status_from,
        status_to=status_to,
        reason=note,
    )
    return {
        "report_id": report_id,
        **shape_lifecycle_version(
            updated, action=action, status_from=status_from
        ),
    }



# --- Lifecycle endpoints (version-scoped; state guard is server-side) --------


@router.post("/{report_id}/versions/{version_number}/submit")
async def submit_report_version(
    report_id: str,
    version_number: int,
    payload: Optional[LifecycleTransitionIn] = None,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """T3 — submit a DRAFT version for review (``DRAFT`` → ``REVIEWED``)."""
    return await _apply_lifecycle_transition(
        repos,
        current_user,
        report_id,
        version_number,
        SUBMIT,
        note=payload.note if payload else None,
    )


@router.post("/{report_id}/versions/{version_number}/request-changes")
async def request_changes_report_version(
    report_id: str,
    version_number: int,
    payload: Optional[LifecycleTransitionIn] = None,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """T7 — request changes on a reviewed version (→ ``CHANGES_REQUESTED``)."""
    return await _apply_lifecycle_transition(
        repos,
        current_user,
        report_id,
        version_number,
        REQUEST_CHANGES,
        note=payload.note if payload else None,
    )


@router.post("/{report_id}/versions/{version_number}/reject")
async def reject_report_version(
    report_id: str,
    version_number: int,
    payload: Optional[LifecycleTransitionIn] = None,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """T8 — reject a reviewed version (``REVIEWED`` → ``REJECTED``)."""
    return await _apply_lifecycle_transition(
        repos,
        current_user,
        report_id,
        version_number,
        REJECT,
        note=payload.note if payload else None,
    )


@router.post("/{report_id}/versions/{version_number}/approve")
async def approve_report_version(
    report_id: str,
    version_number: int,
    payload: Optional[LifecycleTransitionIn] = None,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """T11 — approve a reviewed version (``REVIEWED`` → ``APPROVED``).

    The approval is the **customer organisation's own assertion**; it is not
    independent GHG assurance, verification, certification or audit opinion, and
    is bound to this exact version (a later version does not inherit it).
    """
    return await _apply_lifecycle_transition(
        repos,
        current_user,
        report_id,
        version_number,
        APPROVE,
        note=payload.note if payload else None,
    )



@router.post("/{report_id}/versions/{version_number}/finalize")
async def finalize_report_version(
    report_id: str,
    version_number: int,
    payload: Optional[LifecycleTransitionIn] = None,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """T12 — finalize an approved version (``APPROVED`` → ``FINAL``).

    ``FINAL`` is terminal for the version: it can never leave ``FINAL`` and can
    only be superseded by a *new* version. Finalization freezes the version's
    lifecycle state; producing/storing/hashing the frozen PDF artefact is a
    later bounded stage, so S3 records the state transition and its audit event.
    """
    return await _apply_lifecycle_transition(
        repos,
        current_user,
        report_id,
        version_number,
        FINALIZE,
        note=payload.note if payload else None,
    )


@router.post("/{report_id}/versions", status_code=201)
async def create_report_version(
    report_id: str,
    payload: NewReportVersionIn,
    current_user: AuthUser = Depends(require_org_member()),
    repos: RepositoryBundle = Depends(get_repositories),
) -> dict:
    """T9/T10/T17 — supersede a version with a new ``DRAFT`` version.

    A post-approval/post-final change creates a **new** version rather than
    mutating the approved/final one (ratified immutability rule). The new version
    carries the source version's system ``content`` (engine output is immutable)
    and starts as ``DRAFT`` with its own review/approval cycle. Allowed source
    states: ``CHANGES_REQUESTED``, ``REJECTED``, ``APPROVED``, ``FINAL``.
    """
    report = await repos.reports.get_full(report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    organization_id = report["organization_id"]
    _authorize_lifecycle_action(current_user, NEW_VERSION, organization_id)

    source = await repos.report_versions.get_by_number(
        report_id, payload.from_version_number
    )
    if source is None:
        raise HTTPException(
            status_code=404, detail="source report version not found"
        )
    if not can_create_new_version(source["status"]):
        raise HTTPException(
            status_code=409,
            detail=(
                f"a new version cannot be created from state {source['status']}"
            ),
        )

    version = await repos.report_versions.create(
        report_id=report_id,
        version_number=await repos.report_versions.next_version_number(report_id),
        content=source.get("content") or {},
        file_url=source.get("file_url") or "",
        file_name=source.get("file_name"),
        created_by=current_user.user_id,
        change_summary=(
            f"New version from v{source['version_number']} "
            f"(was {source['status']}) by {current_user.user_id}"
        ),
        is_current=True,
        status=DEFAULT_STATUS,
    )
    await _record_lifecycle_event(
        repos,
        action=NEW_VERSION,
        actor=current_user.user_id,
        organization_id=organization_id,
        report_id=report_id,
        version=version,
        status_from=source["status"],
        status_to=version["status"],
        reason=payload.reason,
        extra={"from_version_number": source["version_number"]},
    )
    return {
        "report_id": report_id,
        "from_version_number": source["version_number"],
        **shape_lifecycle_version(
            version, action=NEW_VERSION, status_from=source["status"]
        ),
    }

