#!/usr/bin/env python3
"""CarbonTally QA Harness — full run orchestrator (spec §34, §39).

The eventual full QA command is:

    python qa_harness/scripts/run_all.py

This orchestrator runs each stage (db → api → workflows → browser → agents),
collects findings, deduplicates, generates reports and computes the
acceptance verdict. It NEVER runs tests when the target stack is
unreachable (SKIPPED stages) and NEVER claims acceptance for untested areas.
"""

from __future__ import annotations

import argparse
import sys
from typing import Any, Dict, List, Optional

from qa_harness.agents.base import openrouter_available
from qa_harness.agents.swarm import AgentSwarm
from qa_harness.core.config import load_config
from qa_harness.core.findings import Finding, normalize_finding, deduplicate_findings
from qa_harness.findings import FindingStore
from qa_harness.reports.backlog import ClineBacklogGenerator
from qa_harness.reports.generator import (
    ReportBundle,
    ReportGenerator,
    acceptance_verdict,
    report_bundle_names,
)
from qa_harness.scripts import run_db, run_api, run_browser, run_workflows, run_agents
from qa_harness.scripts.common import HARNESS_ROOT, add_common_args, load_env_file
from qa_harness.scripts.preflight import git_sha

EXIT_OK = 0
EXIT_SKIPPED = 3
EXIT_FAIL = 1


def run_all(args: argparse.Namespace) -> int:
    config = load_config(HARNESS_ROOT / "config")
    env_name = args.env or config.default_environment
    env = config.environment(env_name)
    sha = git_sha()
    print("CarbonTally QA Harness — full run")
    print("=" * 60)
    print(f"Environment: {env_name}")
    print(f"Git SHA: {sha}")
    print(f"Read-only: {'ENFORCED' if args.read_only else 'DISABLED'}")

    from qa_harness.core.run_context import RunContext
    ctx = RunContext(env=env, env_name=env_name, git_sha=sha, read_only=args.read_only)
    print(f"Run id: {ctx.run_id}")

    stage_exit: Dict[str, int] = {}
    stage_outcome_counts: Dict[str, Dict[str, int]] = {}
    for name, runner in (
        ("db", run_db.run_db),
        ("api", run_api.run_api),
        ("workflows", run_workflows.run_workflows),
        ("browser", run_browser.run_browser),
    ):
        if name == "browser" and args.no_visual:
            print(f"[{name}] SKIPPED — --no-visual")
            stage_exit[name] = EXIT_SKIPPED
            continue
        print(f"\n--- {name} ---")
        try:
            stage_exit[name] = runner(args, ctx=ctx)
        except Exception as exc:
            print(f"[{name}] ERROR: {exc}")
            stage_exit[name] = EXIT_FAIL
        counts = ctx.finish()
        stage_outcome_counts[name] = counts

    raw = ctx.raw_findings()
    normalized = [normalize_finding(f) for f in raw]
    deduplicated = deduplicate_findings(raw)
    ctx.store.save_raw(raw)
    ctx.store.save_normalized(normalized)
    ctx.store.save_deduplicated(deduplicated)
    checks = ctx.checks_executed
    print(f"\nFindings: raw={len(raw)} normalized={len(normalized)} deduplicated={len(deduplicated)}")
    print(f"Deterministic checks executed: {checks}")

    # Optional AI analysis (deterministic findings only, minimal cost).
    observations: List[Any] = []
    if not args.no_ai and openrouter_available() and deduplicated:
        print("\n--- agents ---")
        swarm = AgentSwarm()
        result = swarm.run(deduplicated)
        observations = result.observations
        print(f"Swarm: {result.status.value}")

    unverified = [
        area for area, code in stage_exit.items()
        if code in (EXIT_SKIPPED, EXIT_FAIL)
    ]
    verdict = acceptance_verdict(deduplicated, unverified_areas=unverified)

    bundle = ReportBundle(
        git_sha=sha,
        environment=env_name,
        coverage={
            "stages": stage_exit,
            "unverified_areas": unverified,
            "findings_raw": len(raw),
            "findings_deduplicated": len(deduplicated),
            "stage_outcomes": stage_outcome_counts,
            "checks_executed": checks,
        },
        tests_executed=checks,
        tests_skipped=sum(1 for c in stage_exit.values() if c == EXIT_SKIPPED),
        verdict=verdict,
        notes="Generated by qa_harness/scripts/run_all.py",
    )
    generator = ReportGenerator()
    generator.generate(bundle, deduplicated)
    backlog = ClineBacklogGenerator().generate(deduplicated)
    backlog_path = generator.latest_dir / "CLINE_IMPLEMENTATION_BACKLOG.md"
    ClineBacklogGenerator().write_markdown(backlog, backlog_path)

    print("\n" + "=" * 60)
    print(f"Acceptance verdict: {verdict}")
    for name in report_bundle_names():
        path = generator.latest_dir / name
        print(f"  report: {path}")
    return EXIT_OK


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="CarbonTally QA — full run")
    add_common_args(parser)
    args = parser.parse_args(argv)
    load_env_file()
    return run_all(args)


if __name__ == "__main__":
    raise SystemExit(main())
