# backend/routes/glossary.py
"""
Glossary endpoints for managing glossary terms.
Public endpoints for viewing, admin endpoints for CRUD operations.
"""

from fastapi import APIRouter, Depends, HTTPException, status, Query
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime
from auth import AuthUser, require_auth, require_org_member, require_org_admin, require_permission, require_role  # ✅ Add require_role
from database import get_supabase_client

router = APIRouter(prefix="/api/glossary", tags=["Glossary"])


# ==========================================
# PYDANTIC MODELS
# ==========================================

class GlossaryTermCreate(BaseModel):
    """Request model for creating a glossary term."""
    term: str = Field(..., min_length=1, max_length=255, description="The glossary term")
    definition: str = Field(..., min_length=1, description="Definition of the term")
    category: Optional[str] = Field(None, max_length=100, description="Category (e.g., 'Emissions', 'Regulations')")
    related_terms: Optional[List[str]] = Field(None, description="List of related terms")
    example: Optional[str] = Field(None, description="Example usage")
    
    class Config:
        json_schema_extra = {
            "example": {
                "term": "Carbon Footprint",
                "definition": "The total amount of greenhouse gases generated by our actions.",
                "category": "Emissions",
                "related_terms": ["GHG", "Carbon Emissions"],
                "example": "Our carbon footprint for 2024 was 1,500 tonnes CO2e."
            }
        }

class GlossaryTermUpdate(BaseModel):
    """Request model for updating a glossary term."""
    term: Optional[str] = Field(None, min_length=1, max_length=255)
    definition: Optional[str] = Field(None, min_length=1)
    category: Optional[str] = Field(None, max_length=100)
    related_terms: Optional[List[str]] = None
    example: Optional[str] = None
    
    class Config:
        json_schema_extra = {
            "example": {
                "term": "Carbon Footprint (Updated)",
                "definition": "Updated definition for carbon footprint."
            }
        }

class GlossaryTermResponse(BaseModel):
    """Response model for a glossary term."""
    id: str
    term: str
    definition: str
    category: Optional[str] = None
    related_terms: Optional[List[str]] = None
    example: Optional[str] = None
    is_active: bool
    created_at: datetime
    updated_at: datetime
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "term": "Carbon Footprint",
                "definition": "The total amount of greenhouse gases generated by our actions.",
                "category": "Emissions",
                "related_terms": ["GHG", "Carbon Emissions"],
                "example": "Our carbon footprint for 2024 was 1,500 tonnes CO2e.",
                "is_active": True,
                "created_at": "2024-01-01T00:00:00Z",
                "updated_at": "2024-01-01T00:00:00Z"
            }
        }

class GlossaryListResponse(BaseModel):
    """Response model for glossary list."""
    success: bool
    data: List[GlossaryTermResponse]
    total: int
    categories: Optional[List[str]] = None

# ==========================================
# HELPER FUNCTIONS
# ==========================================

async def get_available_categories(supabase_client) -> List[str]:
    """Get all available categories from glossary."""
    try:
        result = supabase_client.from_('glossary') \
            .select('category') \
            .eq('is_active', True) \
            .execute()
        
        categories = list(set([t.get('category') for t in result.data if t.get('category')])) if result.data else []
        return sorted(categories)
    except Exception as e:
        print(f"⚠️ Error getting categories: {e}")
        return []

# ==========================================
# PUBLIC ENDPOINTS
# ==========================================

@router.get("/", response_model=GlossaryListResponse)
async def get_glossary(
    category: Optional[str] = Query(None, description="Filter by category"),
    search: Optional[str] = Query(None, description="Search in term and definition"),
    limit: int = Query(100, ge=1, le=500, description="Number of results to return"),
    offset: int = Query(0, ge=0, description="Number of results to skip")
):
    """
    Get all glossary terms with optional filtering.
    Public endpoint - no authentication required.
    """
    try:
        supabase = get_supabase_client()
        
        # Build query
        query = supabase.from_('glossary') \
            .select('*') \
            .eq('is_active', True)
        
        # Apply filters
        if category:
            query = query.eq('category', category)
        
        if search:
            query = query.or_(f"term.ilike.%{search}%,definition.ilike.%{search}%")
        
        # ✅ Fix: Remove .clone() and use separate count query
        count_query = supabase.from_('glossary') \
            .select('id', count='exact') \
            .eq('is_active', True)
        
        if category:
            count_query = count_query.eq('category', category)
        
        if search:
            count_query = count_query.or_(f"term.ilike.%{search}%,definition.ilike.%{search}%")
        
        count_result = count_query.execute()
        total = count_result.count or 0
        
        # Get paginated results
        result = query.order('term') \
            .range(offset, offset + limit - 1) \
            .execute()
        
        # Transform data
        terms = []
        for term in (result.data or []):
            terms.append(GlossaryTermResponse(
                id=term['id'],
                term=term['term'],
                definition=term['definition'],
                category=term.get('category'),
                related_terms=term.get('related_terms'),
                example=term.get('example'),
                is_active=term.get('is_active', True),
                created_at=term['created_at'],
                updated_at=term.get('updated_at', term['created_at'])
            ))
        
        # Get available categories
        categories = await get_available_categories(supabase) if not category else [category]
        
        return GlossaryListResponse(
            success=True,
            data=terms,
            total=total,
            categories=categories
        )
        
    except Exception as e:
        print(f"❌ Error getting glossary: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to get glossary: {str(e)}"
        )



@router.get("/categories")
async def get_glossary_categories():
    """
    Get all available glossary categories.
    Public endpoint - no authentication required.
    """
    try:
        supabase = get_supabase_client()
        categories = await get_available_categories(supabase)
        
        return {
            "success": True,
            "categories": categories,
            "total": len(categories)
        }
        
    except Exception as e:
        print(f"❌ Error getting categories: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to get categories: {str(e)}"
        )

@router.get("/search")
async def search_glossary(
    q: str = Query(..., min_length=1),
    category: Optional[str] = None,
    current_user: AuthUser = Depends(require_auth())
):
    """Search glossary terms."""
    try:
        supabase = get_supabase_client()
        
        query = supabase.from_('glossary') \
            .select('*') \
            .ilike('term', f'%{q}%')
        
        if category:
            query = query.eq('category', category)
        
        # ✅ Fix: Remove .clone() and use separate count query
        # Get count
        count_query = supabase.from_('glossary') \
            .select('id', count='exact') \
            .ilike('term', f'%{q}%')
        
        if category:
            count_query = count_query.eq('category', category)
        
        count_result = count_query.execute()
        total = count_result.count or 0
        
        # Get results
        result = query.order('term').execute()
        
        return {
            "success": True,
            "data": result.data,
            "total": total
        }
        
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to search glossary: {str(e)}"
        )


@router.get("/{term_id}", response_model=GlossaryTermResponse)
async def get_glossary_term(term_id: str):
    """
    Get a single glossary term by ID.
    Public endpoint - no authentication required.
    """
    try:
        supabase = get_supabase_client()
        
        result = supabase.from_('glossary') \
            .select('*') \
            .eq('id', term_id) \
            .eq('is_active', True) \
            .maybe_single() \
            .execute()
        
        if not result.data:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Term not found"
            )
        
        term = result.data
        return GlossaryTermResponse(
            id=term['id'],
            term=term['term'],
            definition=term['definition'],
            category=term.get('category'),
            related_terms=term.get('related_terms'),
            example=term.get('example'),
            is_active=term.get('is_active', True),
            created_at=term['created_at'],
            updated_at=term.get('updated_at', term['created_at'])
        )
        
    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ Error getting glossary term: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to get glossary term: {str(e)}"
        )

# ==========================================
# ADMIN ENDPOINTS (FIXED - called require_role())
# ==========================================

@router.post("/", response_model=GlossaryTermResponse)
async def create_glossary_term(
    term_data: GlossaryTermCreate,
    current_user: AuthUser = Depends(require_role(["admin", "data_approver"]))
):
    """
    Create a new glossary term.
    Admin or Data Approver only endpoint.
    """
    try:
        supabase = get_supabase_client()
        
        # Check if client is initialized
        if supabase is None:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Supabase client not initialized"
            )
        
        # Check if term already exists
        existing = supabase.from_('glossary') \
            .select('id') \
            .eq('term', term_data.term) \
            .maybe_single() \
            .execute()
        
        # Handle None response
        if existing is None:
            print("⚠️ Warning: existing query returned None")
            # Continue anyway - we'll try to create
        elif existing.data:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"Term '{term_data.term}' already exists"
            )
        
        # Create term
        now = datetime.now().isoformat()
        result = supabase.from_('glossary') \
            .insert({
                'term': term_data.term,
                'definition': term_data.definition,
                'category': term_data.category,
                'related_terms': term_data.related_terms,
                'example': term_data.example,
                'is_active': True,
                'created_at': now,
                'updated_at': now
            }) \
            .execute()
        
        # Check result
        if result is None:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Database insert returned None"
            )
            
        if not result.data:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Failed to create glossary term - no data returned"
            )
        
        term = result.data[0]
        return GlossaryTermResponse(
            id=term['id'],
            term=term['term'],
            definition=term['definition'],
            category=term.get('category'),
            related_terms=term.get('related_terms'),
            example=term.get('example'),
            is_active=term.get('is_active', True),
            created_at=term['created_at'],
            updated_at=term['updated_at']
        )
        
    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ Error creating glossary term: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to create glossary term: {str(e)}"
        )


@router.put("/{term_id}", response_model=GlossaryTermResponse)
async def update_glossary_term(
    term_id: str,
    term_data: GlossaryTermUpdate,
    current_user: AuthUser = Depends(require_role(["admin", "data_approver"]))  # ✅ Called here
):
    """
    Update a glossary term.
    Admin or Data Approver only endpoint.
    """
    try:
        supabase = get_supabase_client()
        
        # Check if term exists
        existing = supabase.from_('glossary') \
            .select('id, term') \
            .eq('id', term_id) \
            .maybe_single() \
            .execute()
        
        if not existing.data:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Term not found"
            )
        
        # Build update dict
        update_dict = {}
        if term_data.term is not None:
            # Check if new term name conflicts
            if term_data.term != existing.data['term']:
                conflict = supabase.from_('glossary') \
                    .select('id') \
                    .eq('term', term_data.term) \
                    .neq('id', term_id) \
                    .maybe_single() \
                    .execute()
                
                if conflict.data:
                    raise HTTPException(
                        status_code=status.HTTP_409_CONFLICT,
                        detail=f"Term '{term_data.term}' already exists"
                    )
            update_dict['term'] = term_data.term
        
        if term_data.definition is not None:
            update_dict['definition'] = term_data.definition
        if term_data.category is not None:
            update_dict['category'] = term_data.category
        if term_data.related_terms is not None:
            update_dict['related_terms'] = term_data.related_terms
        if term_data.example is not None:
            update_dict['example'] = term_data.example
        
        if not update_dict:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="No fields to update"
            )
        
        update_dict['updated_at'] = datetime.now().isoformat()
        
        # Update term
        result = supabase.from_('glossary') \
            .update(update_dict) \
            .eq('id', term_id) \
            .execute()
        
        if not result.data:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Failed to update glossary term"
            )
        
        term = result.data[0]
        return GlossaryTermResponse(
            id=term['id'],
            term=term['term'],
            definition=term['definition'],
            category=term.get('category'),
            related_terms=term.get('related_terms'),
            example=term.get('example'),
            is_active=term.get('is_active', True),
            created_at=term['created_at'],
            updated_at=term['updated_at']
        )
        
    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ Error updating glossary term: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to update glossary term: {str(e)}"
        )

@router.delete("/{term_id}")
async def delete_glossary_term(
    term_id: str,
    permanent: bool = Query(False, description="Permanently delete or soft delete"),
    current_user: AuthUser = Depends(require_role(["admin"]))  # ✅ Called here
):
    """
    Delete a glossary term.
    Admin only endpoint.
    """
    try:
        supabase = get_supabase_client()
        
        # Check if term exists
        existing = supabase.from_('glossary') \
            .select('id, term') \
            .eq('id', term_id) \
            .maybe_single() \
            .execute()
        
        if not existing.data:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Term not found"
            )
        
        term_name = existing.data['term']
        
        if permanent:
            # Hard delete
            result = supabase.from_('glossary') \
                .delete() \
                .eq('id', term_id) \
                .execute()
            
            message = f"Term '{term_name}' permanently deleted"
        else:
            # Soft delete
            result = supabase.from_('glossary') \
                .update({
                    'is_active': False,
                    'updated_at': datetime.now().isoformat()
                }) \
                .eq('id', term_id) \
                .execute()
            
            message = f"Term '{term_name}' deactivated"
        
        return {
            "success": True,
            "message": message,
            "term_id": term_id,
            "term_name": term_name,
            "permanent": permanent
        }
        
    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ Error deleting glossary term: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to delete glossary term: {str(e)}"
        )

@router.post("/{term_id}/restore")
async def restore_glossary_term(
    term_id: str,
    current_user: AuthUser = Depends(require_role(["admin"]))  # ✅ Called here
):
    """
    Restore a soft-deleted glossary term.
    Admin only endpoint.
    """
    try:
        supabase = get_supabase_client()
        
        # Check if term exists and is inactive
        existing = supabase.from_('glossary') \
            .select('id, term') \
            .eq('id', term_id) \
            .eq('is_active', False) \
            .maybe_single() \
            .execute()
        
        if not existing.data:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Inactive term not found"
            )
        
        # Restore term
        result = supabase.from_('glossary') \
            .update({
                'is_active': True,
                'updated_at': datetime.now().isoformat()
            }) \
            .eq('id', term_id) \
            .execute()
        
        return {
            "success": True,
            "message": f"Term '{existing.data['term']}' restored successfully",
            "term_id": term_id
        }
        
    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ Error restoring glossary term: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to restore glossary term: {str(e)}"
        )
        