import base64
import io
import os
from datetime import datetime
from typing import Dict, List, Any, Optional

import pandas as pd
from fpdf import FPDF
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from supabase import create_client

# ============================================
# HELPER FUNCTIONS
# ============================================

def sanitize_text(text):
    """Safely sanitize text for PDF generation to prevent encoding errors"""
    if not text:
        return ""
    text = str(text)
    # Replace characters that fpdf cannot handle with safe equivalents
    text = text.replace('’', "'").replace('“', '"').replace('”', '"').replace('–', '-')
    text = text.encode('latin-1', 'replace').decode('latin-1')
    return text

# ============================================
# BASE REPORT CLASS
# ============================================

class SustainabilityReportPDF(FPDF):
    """Base class for all sustainability reports"""
    
    def __init__(self, org_name, reporting_year, report_type="SECR"):
        super().__init__()
        self.org_name = org_name
        self.reporting_year = reporting_year
        self.report_type = report_type
        self.set_auto_page_break(auto=True, margin=15)
        
    def header(self):
        self.set_draw_color(200, 200, 200)
        self.line(10, 10, 200, 10)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'{self.report_type} Report | Page {self.page_no()} | Generated by CarbonTally', 0, 0, 'C')
    
    def add_title(self, title):
        self.set_font('Helvetica', 'B', 24)
        self.set_text_color(15, 23, 42)
        self.cell(0, 20, sanitize_text(title), 0, 1, 'C')
        self.ln(5)
    
    def add_section_title(self, title):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(15, 23, 42)
        self.cell(0, 10, sanitize_text(title), 0, 1, 'L')
        self.set_draw_color(22, 163, 74)
        self.line(10, self.get_y(), 50, self.get_y())
        self.ln(5)
    
    def add_subsection_title(self, title):
        self.set_font('Helvetica', 'B', 13)
        self.set_text_color(30, 58, 95)
        self.cell(0, 8, sanitize_text(title), 0, 1, 'L')
        self.ln(3)
    
    def add_paragraph(self, text):
        self.set_font('Helvetica', '', 11)
        self.set_text_color(51, 65, 85)
        self.multi_cell(0, 6, sanitize_text(text))
        self.ln(3)
    
    def add_metric_box(self, label, value, unit="", highlight=False):
        if highlight:
            self.set_fill_color(240, 253, 244)
            self.set_draw_color(22, 163, 74)
            self.rect(10, self.get_y(), 190, 25, 'DF')
            y_start = self.get_y() + 3
            self.set_y(y_start)
        
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(15, 23, 42)
        self.cell(70, 8, sanitize_text(label + ":"), 0, 0, 'L')
        self.set_font('Helvetica', '', 11)
        self.set_text_color(22, 163, 74 if highlight else 51, 65, 85)
        self.cell(0, 8, f"{sanitize_text(value)} {sanitize_text(unit)}", 0, 1, 'L')
        
        if highlight:
            self.set_y(self.get_y() + 5)
    
    def add_table(self, headers, data, column_widths=None):
        if column_widths is None:
            col_count = len(headers)
            column_widths = [190 // col_count] * col_count
        
        self.set_font('Helvetica', 'B', 10)
        self.set_fill_color(241, 245, 249)
        self.set_text_color(15, 23, 42)
        
        for i, header in enumerate(headers):
            self.cell(column_widths[i], 10, sanitize_text(header), 1, 0, 'C', 1)
        self.ln()
        
        self.set_font('Helvetica', '', 9)
        self.set_text_color(51, 65, 85)
        fill = False
        
        for row in data:
            for i, cell in enumerate(row):
                self.cell(column_widths[i], 8, sanitize_text(str(cell)), 1, 0, 'L', fill)
            self.ln()
            fill = not fill


# ============================================
# SECR REPORT (UK)
# ============================================

class SECRReportPDF(SustainabilityReportPDF):
    def __init__(self, org_name, reporting_year):
        super().__init__(org_name, reporting_year, "SECR")
    
    def generate(self, emissions_data, company_number, scope_totals, total_emissions):
        self.add_page()
        self.add_title(self.org_name)
        
        self.set_font('Helvetica', '', 14)
        self.set_text_color(71, 85, 105)
        self.cell(0, 10, 'Streamlined Energy and Carbon Reporting (SECR)', 0, 1, 'C')
        self.cell(0, 10, f'Reporting Period: FY {self.reporting_year}', 0, 1, 'C')
        self.cell(0, 10, f'Company Number: {sanitize_text(company_number)}', 0, 1, 'C')
        self.ln(15)
        
        self.add_section_title('Executive Summary')
        self.add_paragraph(f'This report provides a comprehensive overview of {self.org_name} greenhouse gas emissions for the financial year {self.reporting_year}, in compliance with the UK Streamlined Energy and Carbon Reporting (SECR) regulations.')
        self.ln(8)
        
        self.add_metric_box('Total Emissions', f'{total_emissions:,.2f}', 'kg CO2e', highlight=True)
        self.add_metric_box('Total Emissions', f'{total_emissions/1000:,.2f}', 'tonnes CO2e')
        self.add_paragraph(f'Based on {len(emissions_data)} emission records')
        self.ln(12)
        
        self.add_section_title('Emissions by Scope')
        headers = ['Scope', 'Emissions (kg CO2e)', 'Emissions (tonnes CO2e)']
        data = [[scope, f'{emissions:,.2f}', f'{emissions/1000:,.2f}'] for scope, emissions in scope_totals.items()]
        self.add_table(headers, data)
        self.ln(10)
        
        self.add_section_title('Methodology')
        self.add_paragraph(f'Emissions have been calculated using official UK Government GHG Conversion Factors for Company Reporting ({self.reporting_year}). All conversion factors are sourced from DEFRA and BEIS.')
        self.ln(5)
        
        self.set_font('Helvetica', 'I', 9)
        self.set_text_color(100, 116, 139)
        for text in [
            'Scope 1: Direct emissions from owned or controlled sources.',
            'Scope 2: Indirect emissions from purchased electricity, steam, heating, and cooling.',
            'Scope 3: Other indirect emissions (e.g., business travel, waste disposal).'
        ]:
            self.add_paragraph(text)
        self.ln(10)
        
        self.add_section_title('Compliance Statement')
        self.add_paragraph(f'This report has been prepared in accordance with the Companies (Directors Report) and Limited Liability Partnerships (Energy and Carbon Report) Regulations 2018.')
        self.ln(8)
        
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(22, 163, 74)
        self.cell(0, 6, sanitize_text(f'Report generated on: {datetime.now().strftime("%d %B %Y at %H:%M")}'), 0, 1, 'L')


# ============================================
# CSRD REPORT (EU)
# ============================================

class CSRDReportPDF(SustainabilityReportPDF):
    def __init__(self, org_name, reporting_year):
        super().__init__(org_name, reporting_year, "CSRD")
    
    def generate(self, esg_data, company_number):
        self.add_page()
        self.add_title(self.org_name)
        
        self.set_font('Helvetica', '', 14)
        self.set_text_color(71, 85, 105)
        self.cell(0, 10, 'Corporate Sustainability Reporting Directive (CSRD)', 0, 1, 'C')
        self.cell(0, 10, f'Reporting Period: FY {self.reporting_year}', 0, 1, 'C')
        self.cell(0, 10, f'Company Number: {sanitize_text(company_number)}', 0, 1, 'C')
        self.ln(15)
        
        self.add_section_title('1. Executive Summary')
        self.add_paragraph('This report aligns with the European Commission\'s CSRD requirements, including double materiality assessment and ESRS (European Sustainability Reporting Standards).')
        self.ln(5)
        
        self.add_section_title('2. Environmental Performance')
        self.add_metric_box('Total GHG Emissions (Scope 1-3)', f"{esg_data.get('total_ghg', 0):,.0f}", 'tCO2e', highlight=True)
        self.ln(5)
        
        self.add_section_title('3. Governance Performance')
        governance_data = [
            ['Board Independence', f"{esg_data.get('board_independence', 0)}%"],
            ['Risk Committee', 'Yes' if esg_data.get('risk_committee', False) else 'No'],
            ['Whistleblower Policy', 'Yes' if esg_data.get('whistleblower', False) else 'No']
        ]
        self.add_table(['Metric', 'Value'], governance_data)
        self.ln(5)
        
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(22, 163, 74)
        self.cell(0, 6, sanitize_text(f'Report generated on: {datetime.now().strftime("%d %B %Y at %H:%M")}'), 0, 1, 'L')


# ============================================
# ISSB REPORT (International)
# ============================================

class ISSBReportPDF(SustainabilityReportPDF):
    def __init__(self, org_name, reporting_year):
        super().__init__(org_name, reporting_year, "ISSB")
    
    def generate(self, climate_data, company_number):
        self.add_page()
        self.add_title(self.org_name)
        
        self.set_font('Helvetica', '', 14)
        self.set_text_color(71, 85, 105)
        self.cell(0, 10, 'International Sustainability Standards Board (ISSB)', 0, 1, 'C')
        self.cell(0, 10, f'Climate-related Disclosures - FY {self.reporting_year}', 0, 1, 'C')
        self.cell(0, 10, f'Company Number: {sanitize_text(company_number)}', 0, 1, 'C')
        self.ln(15)
        
        self.add_section_title('1. Governance')
        self.add_paragraph('Oversight of climate-related risks and opportunities is provided by the Board of Directors.')
        self.ln(3)
        
        self.add_section_title('2. Metrics and Targets')
        emissions_data = [
            ['Scope 1', f"{climate_data.get('scope1', 0):,.0f}", 'tCO2e'],
            ['Scope 2', f"{climate_data.get('scope2', 0):,.0f}", 'tCO2e'],
            ['Scope 3', f"{climate_data.get('scope3', 0):,.0f}", 'tCO2e'],
            ['Total', f"{climate_data.get('total_emissions', 0):,.0f}", 'tCO2e']
        ]
        self.add_table(['Metric', 'Value', 'Unit'], emissions_data)
        self.ln(5)
        
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(22, 163, 74)
        self.cell(0, 6, sanitize_text(f'Report generated on: {datetime.now().strftime("%d %B %Y at %H:%M")}'), 0, 1, 'L')


# ============================================
# REPORT GENERATOR FACTORY
# ============================================

class SustainabilityReportGenerator:
    def __init__(self, supabase_client, organization_id, reporting_year):
        self.supabase = supabase_client
        self.organization_id = organization_id
        self.reporting_year = reporting_year
        self.org_data = None
        self.organization_name = None
        self.company_number = None
        
    def _fetch_organization_data(self):
        if self.org_data is None:
            org_res = self.supabase.from_('organizations')\
                .select('name, company_number')\
                .eq('id', self.organization_id)\
                .single()\
                .execute()
            
            if not org_res.data:
                raise HTTPException(status_code=404, detail="Organization not found")
            
            self.org_data = org_res.data
            self.organization_name = sanitize_text(org_res.data.get('name', 'Unknown Organization'))
            self.company_number = sanitize_text(org_res.data.get('company_number', 'N/A'))
        return self.org_data
    
    def _fetch_emissions_data(self, year=None):
        """Fetch emissions data with pagination to handle large datasets"""
        if year is None:
            year = self.reporting_year
            
        all_data = []
        has_more = True
        page = 0
        page_size = 1000  # Supabase max row limit
        
        while has_more:
            start = page * page_size
            end = (page + 1) * page_size - 1
            
            print(f"📄 Fetching page {page + 1} (rows {start} to {end}) for year {year}...")
            
            response = self.supabase.from_('emissions_logs')\
                .select('*, defra_conversion_factors(activity_type, co2e_multiplier, reporting_year), assets(name)')\
                .eq('organization_id', self.organization_id)\
                .gte('start_date', f'{year}-01-01')\
                .lte('start_date', f'{year}-12-31')\
                .range(start, end)\
                .execute()
                
            data = response.data or []
            
            if data:
                all_data.extend(data)
                print(f"✅ Page {page + 1}: {len(data)} records (total so far: {len(all_data)})")
                page += 1
            else:
                has_more = False
                
            # If we got less than page_size, we've reached the end
            if len(data) < page_size:
                has_more = False
        
        print(f"📊 Total records fetched for {year}: {len(all_data)}")
        return all_data
    def _calculate_scope_totals(self, emissions_data):
        scope_totals = {'Scope 1': 0, 'Scope 2': 0, 'Scope 3': 0}
        total_emissions = 0
        
        for record in emissions_data:
            kg_co2e = float(record.get('calculated_kg_co2e', 0))
            total_emissions += kg_co2e
            
            metadata = record.get('metadata', {}) or {}
            defra = record.get('defra_conversion_factors', {}) or {}
            
            scope = metadata.get('scope', 'Unknown')
            if scope == 'Unknown':
                fuel_type = metadata.get('fuel_type', '')
                activity = defra.get('activity_type', '')
                if any(f in activity for f in ['Diesel', 'Petrol', 'Natural Gas', 'LPG']):
                    scope = 'Scope 1'
                elif 'Electricity' in activity:
                    scope = 'Scope 2'
                else:
                    scope = 'Scope 3'
                    
            if scope in scope_totals:
                scope_totals[scope] += kg_co2e
            else:
                scope_totals['Scope 3'] += kg_co2e
                
        return scope_totals, total_emissions

    def generate_secr_report(self):
        self._fetch_organization_data()
        emissions_data = self._fetch_emissions_data()
        if not emissions_data:
            raise HTTPException(status_code=404, detail="No emissions data found for this organization.")
        
        scope_totals, total_emissions = self._calculate_scope_totals(emissions_data)
        pdf = SECRReportPDF(self.organization_name, self.reporting_year)
        pdf.generate(emissions_data, self.company_number, scope_totals, total_emissions)
        
        pdf_output = pdf.output(dest='S').encode('latin-1')
        return {
            "status": "success", "report_type": "SECR",
            "pdf_base64": base64.b64encode(pdf_output).decode('utf-8'),
            "filename": f"SECR_Report_{self.organization_name}_{self.reporting_year}.pdf"
        }
    
    def generate_csrd_report(self):
        self._fetch_organization_data()
        esg_data = {'total_ghg': 4500, 'board_independence': 60, 'risk_committee': True, 'whistleblower': True}
        pdf = CSRDReportPDF(self.organization_name, self.reporting_year)
        pdf.generate(esg_data, self.company_number)
        
        pdf_output = pdf.output(dest='S').encode('latin-1')
        return {
            "status": "success", "report_type": "CSRD",
            "pdf_base64": base64.b64encode(pdf_output).decode('utf-8'),
            "filename": f"CSRD_Report_{self.organization_name}_{self.reporting_year}.pdf"
        }
    
    def generate_issb_report(self):
        self._fetch_organization_data()
        climate_data = {'scope1': 1500, 'scope2': 1200, 'scope3': 1800, 'total_emissions': 4500}
        pdf = ISSBReportPDF(self.organization_name, self.reporting_year)
        pdf.generate(climate_data, self.company_number)
        
        pdf_output = pdf.output(dest='S').encode('latin-1')
        return {
            "status": "success", "report_type": "ISSB",
            "pdf_base64": base64.b64encode(pdf_output).decode('utf-8'),
            "filename": f"ISSB_Report_{self.organization_name}_{self.reporting_year}.pdf"
        }

    def generate_auditor_excel(self):
        self._fetch_organization_data()
        emissions_data = self._fetch_emissions_data()
        
        if not emissions_data:
            raise HTTPException(status_code=404, detail="No emissions data found to export. Please upload and approve data first.")
            
        scope_totals, total_emissions = self._calculate_scope_totals(emissions_data)
        output = io.BytesIO()
        
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            # Sheet 1: Executive Summary
            summary_data = {
                'Metric': ['Organization', 'Reporting Year', 'Total Emissions (kg CO2e)', 'Scope 1', 'Scope 2', 'Scope 3', 'Total Records'],
                'Value': [self.organization_name, self.reporting_year, total_emissions, scope_totals['Scope 1'], scope_totals['Scope 2'], scope_totals['Scope 3'], len(emissions_data)]
            }
            pd.DataFrame(summary_data).to_excel(writer, sheet_name='01_Executive_Summary', index=False)
            
            # Sheet 2: Granular Transaction Log
            log_data = []
            for record in emissions_data:
                metadata = record.get('metadata', {}) or {}
                defra = record.get('defra_conversion_factors', {}) or {}
                asset = record.get('assets', {}) or {}
                
                log_data.append({
                    'Date': record.get('start_date', ''),
                    'Facility / Asset': asset.get('name', metadata.get('asset_name', 'Unassigned')),
                    'Activity Type': defra.get('activity_type', metadata.get('fuel_type', 'Unknown')),
                    'Quantity': record.get('raw_quantity', 0),
                    'Calculated kgCO2e': record.get('calculated_kg_co2e', 0),
                    'Source': metadata.get('source', 'Manual Entry')
                })
            pd.DataFrame(log_data).to_excel(writer, sheet_name='02_Granular_Transaction_Log', index=False)

        output.seek(0)
        return {
            "status": "success", "report_type": "AUDITOR_EXCEL",
            "file_base64": base64.b64encode(output.read()).decode('utf-8'),
            "filename": f"CarbonTally_Auditor_Export_{self.organization_name}_{self.reporting_year}.xlsx"
        }

# ============================================
# API ENDPOINTS
# ============================================

router = APIRouter()

class ReportRequest(BaseModel):
    organization_id: str
    reporting_year: int
    report_type: str

@router.post("/generate-sustainability-report")
async def generate_sustainability_report(request: ReportRequest):
    try:
        supabase_url = os.getenv("SUPABASE_URL")
        supabase_key = os.getenv("SUPABASE_SERVICE_KEY")
        supabase_client = create_client(supabase_url, supabase_key)
        
        generator = SustainabilityReportGenerator(supabase_client, request.organization_id, request.reporting_year)
        
        if request.report_type == 'SECR':
            result = generator.generate_secr_report()
        elif request.report_type == 'CSRD':
            result = generator.generate_csrd_report()
        elif request.report_type == 'ISSB':
            result = generator.generate_issb_report()
        elif request.report_type == 'AUDITOR_EXCEL':
            result = generator.generate_auditor_excel()
        else:
            raise HTTPException(status_code=400, detail="Invalid report type")
            
        return result
        
    except HTTPException:
        raise
    except Exception as e:
        import traceback
        print(f"--- REPORT GENERATION ERROR ---\n{traceback.format_exc()}\n-------------------")
        raise HTTPException(status_code=500, detail=f"Report generation failed: {str(e)}")