"""Artifact writers (JSON / SQL / Markdown reports) and database loader.

The SQL artifact is the canonical, portable deliverable: idempotent
``INSERT ... SELECT ... WHERE NOT EXISTS`` statements that match the RC2
natural-key unique index (``reporting_year, activity_type,
COALESCE(country,'GB'), COALESCE(unit,'{no-unit}'), COALESCE(scope,'{no-scope}')``)
so they are safe on both the narrow and widened index variants.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime
from decimal import Decimal
from pathlib import Path
from typing import Any, Optional

from .models import EmissionFactor, ImportResult

logger = logging.getLogger(__name__)

SCHEMA = "public"
TABLE = "emission_factors"
NO_UNIT = "{no-unit}"
NO_SCOPE = "{no-scope}"

# Query parameters psycopg2 understands; anything else (e.g. Supabase pooler's
# ``?schema=public``) is dropped so the DSN connects cleanly.
_PSYCOPG2_URI_PARAMS = {
    "sslmode", "sslrootcert", "sslcert", "sslkey", "sslpassword",
    "connect_timeout", "application_name", "options", "keepalives",
    "keepalives_idle", "target_session_attrs",
}


def _sanitize_dsn(dsn: str) -> str:
    """Return a psycopg2-compatible DSN (drops non-standard URI query params)."""
    if "?" not in dsn:
        return dsn
    base, _, query = dsn.partition("?")
    pairs = [
        item
        for item in query.split("&")
        if "=" in item and item.partition("=")[0] in _PSYCOPG2_URI_PARAMS
    ]
    return base + ("?" + "&".join(pairs) if pairs else "")


# ---------------------------------------------------------------------------
# SQL literal helpers
# ---------------------------------------------------------------------------
def _sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _sql_nullable(value: Optional[str]) -> str:
    return "NULL" if value is None else _sql_str(value)


def _sql_decimal(value: Decimal) -> str:
    return format(value, "f")


# ---------------------------------------------------------------------------
# SQL generation
# ---------------------------------------------------------------------------
def generate_sql(factors: list[EmissionFactor], schema: str = SCHEMA) -> str:
    """Generate one idempotent INSERT statement per emission factor."""
    if not factors:
        return "-- No factors to import.\n"

    year = factors[0].reporting_year
    lines: list[str] = [
        "-- ============================================================================",
        f"-- CarbonTally — DEFRA {year} emission factors import (idempotent)",
        "-- Target table: public.emission_factors",
        f"-- Factor set: {factors[0].factor_set}  |  Source: {factors[0].factor_source}",
        "-- Generated by src.commands.import_defra at "
        + datetime.now().isoformat(timespec="seconds"),
        "-- Re-running this file never creates duplicate rows: each INSERT only",
        "-- fires when no row with the same natural key already exists.",
        "-- ============================================================================",
        "",
        "BEGIN;",
        "",
    ]

    for factor in factors:
        lines.extend(_insert_statement(factor, schema))

    lines.append("")
    lines.append("COMMIT;")
    return "\n".join(lines)


def _insert_statement(factor: EmissionFactor, schema: str) -> list[str]:
    year = factor.reporting_year
    unit_lit = factor.unit or NO_UNIT
    scope_lit = factor.scope or NO_SCOPE

    where = (
        "    SELECT 1 FROM {schema}.{table}\n"
        "     WHERE reporting_year = {year}\n"
        "       AND activity_type = {label}\n"
        "       AND COALESCE(country, 'GB') = {country}\n"
        "       AND COALESCE(unit, '{no_unit}') = {unit}\n"
        "       AND COALESCE(scope, '{no_scope}') = {scope}"
    ).format(
        schema=schema,
        table=TABLE,
        year=year,
        label=_sql_str(factor.activity_type),
        country=_sql_str(factor.country or "GB"),
        no_unit=NO_UNIT,
        unit=_sql_str(unit_lit),
        no_scope=NO_SCOPE,
        scope=_sql_str(scope_lit),
    )

    insert = (
        "INSERT INTO {schema}.{table}\n"
        "    (reporting_year, activity_type, co2e_multiplier, unit, scope,\n"
        "     factor_source, factor_set, country, updated_at)\n"
        "SELECT {year}, {label}, {multiplier}, {unit}, {scope},\n"
        "       {source}, {factor_set}, {country}, NOW()\n"
        "WHERE NOT EXISTS (\n{where}\n);"
    ).format(
        schema=schema,
        table=TABLE,
        year=year,
        label=_sql_str(factor.activity_type),
        multiplier=_sql_decimal(factor.co2e_multiplier),
        unit=_sql_nullable(factor.unit),
        scope=_sql_nullable(factor.scope),
        source=_sql_str(factor.factor_source),
        factor_set=_sql_str(factor.factor_set),
        country=_sql_str(factor.country or "GB"),
        where=where,
    )

    return [
        "-- DEFRA ID {id} | source row {row} | sheet {sheet}".format(
            id=factor.defra_id, row=factor.row_number, sheet=factor.sheet_name
        ),
        insert,
        "",
    ]


def write_sql_artifact(factors: list[EmissionFactor], output_dir: Path, suffix: str = "") -> str:
    """Write the SQL import file; returns its path."""
    sql_dir = output_dir / "sql"
    sql_dir.mkdir(parents=True, exist_ok=True)
    year = factors[0].reporting_year if factors else "unknown"
    path = sql_dir / f"import_defra_{year}{suffix}.sql"
    path.write_text(generate_sql(factors), encoding="utf-8")
    logger.info("SQL artifact written: %s", path)
    return str(path)


# ---------------------------------------------------------------------------
# JSON artifacts
# ---------------------------------------------------------------------------
def _dump_json(target: Path, data: Any) -> None:
    target.write_text(
        json.dumps(data, indent=2, ensure_ascii=False, default=str),
        encoding="utf-8",
    )


def write_json_artifacts(result: ImportResult, output_dir: Path) -> list[str]:
    """Write all JSON artifacts; returns the list of written paths."""
    json_dir = output_dir / "json"
    json_dir.mkdir(parents=True, exist_ok=True)

    payloads: list[tuple[str, Any]] = [
        ("workbook_analysis.json", result.analysis.as_dict()),
        ("worksheet_analysis.json", [w.as_dict() for w in result.analysis.worksheets]),
        ("mapping_report.json", _mapping_report_payload(result)),
        ("imported_rows.json", [f.as_dict() for f in result.validation.factors]),
        ("skipped_rows.json", [s.as_dict() for s in result.validation.skipped]),
        ("duplicates.json", [d.as_dict() for d in result.validation.duplicates]),
        ("validation_report.json", result.validation.as_dict()),
        (
            "import_summary.json",
            {
                "generated_at": datetime.now().isoformat(timespec="seconds"),
                "config": result.config,
                "stats": result.stats.as_dict(),
                "db": result.db,
            },
        ),
    ]

    written: list[str] = []
    for name, data in payloads:
        target = json_dir / name
        _dump_json(target, data)
        written.append(str(target))
    logger.info("JSON artifacts written to %s", json_dir)
    return written


def _mapping_report_payload(result: ImportResult) -> dict[str, Any]:
    data_sheets = [w for w in result.analysis.worksheets if w.sheet_type == "data"]
    return {
        "reporting_year": result.analysis.reporting_year,
        "data_sheets": [
            {
                "name": w.name,
                "header_row": w.header_row,
                "columns": [{"label": label, "index": idx} for label, idx in w.columns],
            }
            for w in data_sheets
        ],
        "column_mapping": {
            "ID": "defra_id (reference only — no DB column)",
            "Scope": "scope",
            "Level 1": "activity_type (label component)",
            "Level 2": "activity_type (label component)",
            "Level 3": "activity_type (label component)",
            "Level 4": "activity_type (label component)",
            "Column Text": "activity_type (label component)",
            "UOM": "unit",
            "GHG/Unit": "activity_type (label component)",
            "GHG Conversion Factor <year>": "co2e_multiplier",
            "reporting_year (from header)": "reporting_year",
        },
        "constant_values": {
            "factor_source": "DEFRA-DESNZ",
            "factor_set": "DEFRA-<year>",
            "country": "GB",
        },
    }


# ---------------------------------------------------------------------------
# Markdown report artifacts
# ---------------------------------------------------------------------------
def write_reports(result: ImportResult, output_dir: Path) -> list[str]:
    """Write the Markdown report set; returns the list of written paths."""
    report_dir = output_dir / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)

    payloads: list[tuple[str, str]] = [
        ("workbook_analysis.md", _report_workbook_analysis(result)),
        ("worksheet_analysis.md", _report_worksheet_analysis(result)),
        ("mapping_report.md", _report_mapping(result)),
        ("validation_report.md", _report_validation(result)),
        ("import_summary.md", _report_summary(result)),
    ]

    written: list[str] = []
    for name, body in payloads:
        target = report_dir / name
        target.write_text(body, encoding="utf-8")
        written.append(str(target))
    logger.info("Markdown reports written to %s", report_dir)
    return written


def _report_workbook_analysis(result: ImportResult) -> str:
    meta = result.analysis.meta
    lines = [
        "# Workbook Analysis",
        "",
        "| Property | Value |",
        "|---|---|",
        f"| Source | `{meta.source_path}` |",
        f"| Size (bytes) | {meta.file_size_bytes} |",
        f"| SHA-256 | `{meta.file_sha256}` |",
        f"| Title | {meta.title} |",
        f"| Status | {meta.status} |",
        f"| Version | {meta.version} |",
        f"| Year | {meta.year} |",
        f"| Next publication date | {meta.next_publication_date} |",
        f"| Factor set (label) | {meta.factor_set_label} |",
        f"| Producer | {meta.producer} |",
        f"| Contact | {meta.contact} |",
        "",
        f"Reporting year resolved from the factor column header: **{result.analysis.reporting_year}**.",
        "",
        "## Worksheets",
        "",
        "| # | Worksheet | Type | Rows | Columns | Header row |",
        "|---|---|---|---|---|---|",
    ]
    for idx, ws in enumerate(result.analysis.worksheets, start=1):
        lines.append(
            f"| {idx} | {ws.name} | {ws.sheet_type} | {ws.max_row} | {ws.max_col} | {ws.header_row or '-'} |"
        )
    lines.append("")
    lines.append("## Data worksheets (contain emission factors)")
    if result.analysis.data_sheet_names:
        for name in result.analysis.data_sheet_names:
            lines.append(f"- `{name}`")
    else:
        lines.append("- *(none found)*")
    return "\n".join(lines)


def _report_worksheet_analysis(result: ImportResult) -> str:
    lines = ["# Worksheet Analysis", ""]
    for ws in result.analysis.worksheets:
        lines.append(f"## `{ws.name}`  —  type: `{ws.sheet_type}`")
        lines.append("")
        lines.append(f"- Rows: {ws.max_row}, Columns: {ws.max_col}")
        if ws.header_row:
            lines.append(f"- Data header row: {ws.header_row}")
        if ws.columns:
            lines.append("- Detected columns:")
            for label, idx in ws.columns:
                lines.append(f"  - `{label}` → column {idx}")
        if ws.data_row_count is not None:
            lines.append(f"- Rows below header: {ws.data_row_count}")
        if ws.notes:
            lines.append("- Notes:")
            for note in ws.notes:
                lines.append(f"  - {note}")
        lines.append("")
    return "\n".join(lines)



def _report_mapping(result: ImportResult) -> str:
    lines = [
        "# Mapping Report",
        "",
        f"Reporting year: **{result.analysis.reporting_year}**",
        "",
        "## Worksheets containing emission factors",
        "",
    ]
    for ws in result.analysis.worksheets:
        if ws.sheet_type != "data":
            continue
        lines.append(f"### `{ws.name}` (header row {ws.header_row})")
        lines.append("")
        lines.append("| Workbook column | Target DB field | Notes |")
        lines.append("|---|---|---|")
        for label, _idx in ws.columns:
            target = {
                "ID": "`defra_id` (reference only — no DB column)",
                "Scope": "`scope`",
                "Level 1": "`activity_type` (label component)",
                "Level 2": "`activity_type` (label component)",
                "Level 3": "`activity_type` (label component)",
                "Level 4": "`activity_type` (label component)",
                "Column Text": "`activity_type` (label component)",
                "UOM": "`unit`",
                "GHG/Unit": "`activity_type` (label component)",
            }.get(label)
            if target is None and label.startswith("GHG Conversion Factor"):
                target = "`co2e_multiplier` (exact decimal, unrounded)"
            if target is None:
                continue
            lines.append(f"| `{label}` | {target} | |")
        lines.append("")
    lines.append("## Constant values applied")
    lines.append("")
    lines.append("| DB field | Value |")
    lines.append("|---|---|")
    lines.append(f"| `reporting_year` | {result.config.get('reporting_year')} |")
    lines.append(f"| `factor_source` | `{result.config.get('factor_source')}` |")
    lines.append(f"| `factor_set` | `{result.config.get('factor_set')}` |")
    lines.append(f"| `country` | `{result.config.get('country')}` |")
    lines.append("")
    lines.append("## Natural key (idempotency)")
    lines.append("")
    lines.append(
        "`(reporting_year, activity_type, COALESCE(country,'GB'), "
        "COALESCE(unit,'{no-unit}'), COALESCE(scope,'{no-scope}'))`"
    )
    return "\n".join(lines)


def _report_validation(result: ImportResult) -> str:
    stats = result.stats
    lines = [
        "# Validation Report",
        "",
        f"Validated: **{stats.imported}** rows will be imported.",
        "",
        "## Totals",
        "",
        "| Metric | Count |",
        "|---|---|",
        f"| Rows scanned (data sheets) | {stats.rows_scanned} |",
        f"| Rows parsed | {stats.rows_parsed} |",
        f"| Rows with DEFRA ID | {stats.rows_with_id} |",
        f"| Rows with a published factor value | {stats.factors_with_value} |",
        f"| Imported | {stats.imported} |",
        f"| Skipped — no factor value | {stats.skipped_no_factor} |",
        f"| Skipped — unparseable factor | {stats.skipped_unparseable} |",
        f"| Skipped — no activity label | {stats.skipped_no_label} |",
        f"| Skipped — no DEFRA ID | {stats.skipped_no_id} |",
        f"| Skipped — validation error | {stats.skipped_validation} |",
        f"| Duplicates (natural key) | {stats.duplicates} |",
        "",
    ]
    warnings = [issue for issue in result.validation.issues if issue.severity == "warning"]
    if warnings:
        lines.append("## Findings (warnings)")
        lines.append("")
        lines.append("| Row | DEFRA ID | Field | Message |")
        lines.append("|---|---|---|---|")
        for issue in warnings:
            lines.append(
                f"| {issue.row_number} | {issue.defra_id} | `{issue.field}` | {issue.message} |"
            )
        lines.append("")
    return "\n".join(lines)


def _report_summary(result: ImportResult) -> str:
    lines = [
        "# Import Summary",
        "",
        f"Generated: {datetime.now().isoformat(timespec='seconds')}",
        "",
        "## Configuration",
        "",
        "| Option | Value |",
        "|---|---|",
    ]
    for key, value in result.config.items():
        lines.append(f"| {key} | `{value}` |")
    lines.append("")
    lines.append("## Statistics")
    lines.append("")
    lines.append("| Metric | Count |")
    lines.append("|---|---|")
    for key, value in result.stats.as_dict().items():
        lines.append(f"| {key} | {value} |")
    if result.db:
        lines.append("")
        lines.append("## Database result")
        lines.append("")
        lines.append("| Key | Value |")
        lines.append("|---|---|")
        for key, value in result.db.items():
            lines.append(f"| {key} | `{value}` |")
    return "\n".join(lines)



# ---------------------------------------------------------------------------
# Database loader
# ---------------------------------------------------------------------------
def load_to_db(
    factors: list[EmissionFactor],
    mode: str,
    db_url: Optional[str],
    supabase_url: Optional[str],
    supabase_key: Optional[str],
    schema: str = SCHEMA,
) -> dict[str, Any]:
    """Write factors to the database using the best available backend.

    Prefers a direct Postgres connection (psycopg2) when a DSN is supplied;
    falls back to the Supabase client (service role) when only
    ``SUPABASE_URL`` + ``SUPABASE_SERVICE_KEY`` are available.

    ``mode`` is ``sync`` (upsert by natural key) or ``replace`` (delete the
    factor set first, then insert — an exact, idempotent refresh).
    """
    if db_url:
        return load_with_psycopg2(factors, mode, db_url, schema)
    if supabase_url and supabase_key:
        return load_with_supabase(factors, mode, supabase_url, supabase_key)
    raise RuntimeError(
        "No database credentials available. Set DATABASE_URL (or SUPABASE_DB_URL/"
        "POSTGRES_URL) for a direct connection, or SUPABASE_URL + "
        "SUPABASE_SERVICE_KEY for the Supabase client."
    )


def load_with_psycopg2(
    factors: list[EmissionFactor],
    mode: str,
    dsn: str,
    schema: str = SCHEMA,
) -> dict[str, Any]:
    """Upsert factors through a direct Postgres connection in one transaction."""
    import psycopg2

    inserts = 0
    updates = 0
    deleted = 0
    table = f"{schema}.{TABLE}"
    conn = psycopg2.connect(dsn)
    try:
        with conn:
            with conn.cursor() as cur:
                if mode == "replace" and factors:
                    cur.execute(
                        f"DELETE FROM {table} WHERE factor_set = %s",
                        (factors[0].factor_set,),
                    )
                    deleted = cur.rowcount
                for factor in factors:
                    cur.execute(
                        "SELECT id FROM {table} WHERE "
                        "reporting_year = %s AND activity_type = %s AND "
                        "COALESCE(country, 'GB') = %s AND "
                        "COALESCE(unit, '{no_unit}') = %s AND "
                        "COALESCE(scope, '{no_scope}') = %s".format(
                            table=table, no_unit=NO_UNIT, no_scope=NO_SCOPE
                        ),
                        (
                            factor.reporting_year,
                            factor.activity_type,
                            factor.country or "GB",
                            factor.unit or NO_UNIT,
                            factor.scope or NO_SCOPE,
                        ),
                    )
                    existing = cur.fetchone()
                    if existing is not None:
                        cur.execute(
                            "UPDATE {table} SET co2e_multiplier = %s, unit = %s, "
                            "scope = %s, factor_source = %s, factor_set = %s, "
                            "country = %s, updated_at = NOW() WHERE id = %s".format(
                                table=table
                            ),
                            (
                                factor.co2e_multiplier,
                                factor.unit,
                                factor.scope,
                                factor.factor_source,
                                factor.factor_set,
                                factor.country,
                                existing[0],
                            ),
                        )
                        updates += 1
                    else:
                        cur.execute(
                            "INSERT INTO {table} (reporting_year, activity_type, "
                            "co2e_multiplier, unit, scope, factor_source, factor_set, "
                            "country) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)".format(
                                table=table
                            ),
                            (
                                factor.reporting_year,
                                factor.activity_type,
                                factor.co2e_multiplier,
                                factor.unit,
                                factor.scope,
                                factor.factor_source,
                                factor.factor_set,
                                factor.country,
                            ),
                        )
                        inserts += 1
    finally:
        conn.close()
    return {
        "backend": "psycopg2",
        "mode": mode,
        "inserted": inserts,
        "updated": updates,
        "deleted_before_insert": deleted,
        "total_processed": len(factors),
    }



def load_with_supabase(
    factors: list[EmissionFactor],
    mode: str,
    url: str,
    key: str,
) -> dict[str, Any]:
    """Upsert factors through the Supabase client (service role)."""
    from supabase import create_client

    client = create_client(url.strip(), key.strip())
    table = client.table(TABLE)
    inserts = 0
    updates = 0
    deleted = 0

    if mode == "replace" and factors:
        result = table.delete().eq("factor_set", factors[0].factor_set).execute()
        deleted = len(result.data or [])

    for factor in factors:
        query = (
            table.select("id")
            .eq("reporting_year", factor.reporting_year)
            .eq("activity_type", factor.activity_type)
            .eq("country", factor.country or "GB")
        )
        if factor.unit is None:
            query = query.is_("unit", None)
        else:
            query = query.eq("unit", factor.unit)
        if factor.scope is None:
            query = query.is_("scope", None)
        else:
            query = query.eq("scope", factor.scope)

        result = query.maybe_single().execute()
        existing = result.data

        multiplier = format(factor.co2e_multiplier, "f")
        if existing:
            table.update(
                {
                    "co2e_multiplier": multiplier,
                    "unit": factor.unit,
                    "scope": factor.scope,
                    "factor_source": factor.factor_source,
                    "factor_set": factor.factor_set,
                    "country": factor.country,
                    "updated_at": datetime.now().isoformat(),
                }
            ).eq("id", existing["id"]).execute()
            updates += 1
        else:
            table.insert(
                {
                    "reporting_year": factor.reporting_year,
                    "activity_type": factor.activity_type,
                    "co2e_multiplier": multiplier,
                    "unit": factor.unit,
                    "scope": factor.scope,
                    "factor_source": factor.factor_source,
                    "factor_set": factor.factor_set,
                    "country": factor.country,
                }
            ).execute()
            inserts += 1

    return {
        "backend": "supabase",
        "mode": mode,
        "inserted": inserts,
        "updated": updates,
        "deleted_before_insert": deleted,
        "total_processed": len(factors),
    }

