"""CarbonTally domain layer (Backend v2.1 §9, ADR-10).

Pure Python. No framework, database, API or Supabase imports — every object is
an immutable frozen dataclass and every contract is expressed here so the
engine and infrastructure layers implement against this package.
"""

from .audit import AuditEntry, AuditQuery, AuditTrail
from .benchmarking import (
    BenchmarkAvailability,
    BenchmarkMetric,
    BenchmarkRequest,
    BenchmarkResult,
)
from .calculation import (
    CalculationMethodology,
    CalculationResult,
    CalculationSnapshot,
    EmissionLog,
    EmissionsAggregate,
    VerificationResult,
)
from .document import (
    Document,
    ExtractionField,
    ExtractionResult,
    ExtractedPage,
    ExtractedTable,
)
from .factor import EmissionFactor, FactorSet, FactorSetMetadata
from .matching import (
    FactorAlias,
    FactorSearch,
    MatchRequest,
    MatchResult,
    MatchingPipelineConfig,
    MatchingStage,
    StageResult,
    Suggestion,
)
from .organization import Asset, Facility, Organization, OrganizationMember, OrganizationMetadata
from .provider import (
    DiscoveredSheet,
    DiscoveryResult,
    ImportBatch,
    ImportError,
    ImportResult,
    NormalisedFactor,
    ProviderInfo,
    ProviderVersion,
    RawFactorRow,
)
from .report import GeneratedReport, ReportRequest, ReportSection, ReportTemplate
from .validation import ValidationIssue, ValidationReport, ValidationRequest, ValidationSeverity
from .workflow import (
    DOCUMENT_PIPELINE,
    CalculationCompleted,
    CalculationRequested,
    DocumentUploaded,
    DomainEvent,
    ExtractionCompleted,
    ExtractionRequested,
    FactorMatched,
    FactorNotFound,
    FieldsExtracted,
    ImportCompleted,
    ImportRolledBack,
    ImportStarted,
    ReportGenerated,
    Saga,
    SagaStep,
    Transition,
    ValidationFailed,
    WorkflowDefinition,
    WorkflowStateChanged,
)

__all__ = [
    "AuditEntry",
    "AuditQuery",
    "AuditTrail",
    "Asset",
    "BenchmarkAvailability",
    "BenchmarkMetric",
    "BenchmarkRequest",
    "BenchmarkResult",
    "CalculationCompleted",
    "CalculationMethodology",
    "CalculationRequested",
    "CalculationResult",
    "CalculationSnapshot",
    "DOCUMENT_PIPELINE",
    "DiscoveredSheet",
    "DiscoveryResult",
    "Document",
    "DocumentUploaded",
    "DomainEvent",
    "EmissionFactor",
    "EmissionLog",
    "EmissionsAggregate",
    "ExtractionCompleted",
    "ExtractionField",
    "ExtractionRequested",
    "ExtractionResult",
    "ExtractedPage",
    "ExtractedTable",
    "FactorAlias",
    "FactorMatched",
    "FactorNotFound",
    "FactorSearch",
    "FactorSet",
    "FactorSetMetadata",
    "FieldsExtracted",
    "Facility",
    "GeneratedReport",
    "ImportBatch",
    "ImportCompleted",
    "ImportError",
    "ImportResult",
    "ImportRolledBack",
    "ImportStarted",
    "MatchRequest",
    "MatchResult",
    "MatchingPipelineConfig",
    "MatchingStage",
    "NormalisedFactor",
    "Organization",
    "OrganizationMember",
    "OrganizationMetadata",
    "ProviderInfo",
    "ProviderVersion",
    "RawFactorRow",
    "ReportGenerated",
    "ReportRequest",
    "ReportSection",
    "ReportTemplate",
    "Saga",
    "SagaStep",
    "StageResult",
    "Suggestion",
    "Transition",
    "ValidationFailed",
    "ValidationIssue",
    "ValidationReport",
    "ValidationRequest",
    "ValidationSeverity",
    "VerificationResult",
    "WorkflowDefinition",
    "WorkflowStateChanged",
]
